# sample data of communities with barangay names along with population and distances from each shelter
Community = [
    {"name": "Balite", "population": 602, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.38, 
        "F. Mendoza Memorial Elem Sch.": 4.20, 
        "Calumpit Sports Complex": 4.38,
        "Gatbuca Basketball Court": 4.77,
        "San Miguel Meysulao High School": 9.35,
        "Doña Damiana Elem School": 9.26,
        "Danga Dike": 8.15,
        "Meysulao Multipurpose/E.C.": 6.59,
        "Calizon Dike": 4.78,
        "San Marcos Elem. Sch.": 1.14,
        "San Marcos National H.S.": 1.67,
        "GMA Kapuso E.C.": 1.37,
        "NV9 Multi-Purpose": 3.28,
        "Frances E.C.": 4.77,
        "Balungao E.C.": 4.28,
        "Gugo E.C.": 4.79,
        "San Marcos E.C.": 1.01,
        "San Jose E.C.": 9.61,
        "MEYTO Multi-Purpose/ E.C.": 9.62,
        "Barangay Hall Bulusan": 6.84,
        "Brgy. Hall Sta. Lucia": 7.17,
        "Mun. Covered Court": 4.02,
        "Pio Cruzcosa Empty Lot": 2.35,
        "Palimbang Empty Lot": 2.02,
        "Iba O'Este Empty Lot 1": 3.29,
        "Iba O'Este Empty Lot 2": 2.84,
        "Caniogan Empty Lot": 2.84,
        "Iba O'Este Empty Lot 3": 2.88,
        "Iba O'Este Empty Lot 4": 3.02,
        "Caniogan Empty Lot 2": 3.02,
        "Corazon Empty Lot 1": 3.24,
        "Corazon Empty Lot 2": 3.38,
        "Gugo Empty Lot": 3.38,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Balungao", "population": 687, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.07, 
        "F. Mendoza Memorial Elem Sch.": 0.91, 
        "Calumpit Sports Complex": 1.07,
        "Gatbuca Basketball Court": 1.46,
        "San Miguel Meysulao High School": 6.04,
        "Doña Damiana Elem School": 5.95,
        "Danga Dike": 4.84,
        "Meysulao Multipurpose/E.C.": 2.55,
        "Calizon Dike": 0.67,
        "San Marcos Elem. Sch.": 3.17,
        "San Marcos National H.S.": 3.28,
        "GMA Kapuso E.C.": 5.51,
        "NV9 Multi-Purpose": 3.18,
        "Frances E.C.": 1.46,
        "Balungao E.C.": 0,
        "Gugo E.C.": 2.34,
        "San Marcos E.C.": 3.26,
        "San Jose E.C.": 5.57,
        "MEYTO Multi-Purpose/ E.C.": 5.58,
        "Barangay Hall Bulusan": 2.80,
        "Brgy. Hall Sta. Lucia": 3.13,
        "Mun. Covered Court": 0.39,
        "Pio Cruzcosa Empty Lot": 5.03,
        "Palimbang Empty Lot": 2.34,
        "Iba O'Este Empty Lot 1": 2.38,
        "Iba O'Este Empty Lot 2": 1.57,
        "Caniogan Empty Lot": 1.52,
        "Iba O'Este Empty Lot 3": 1.48,
        "Iba O'Este Empty Lot 4": 1.34,
        "Caniogan Empty Lot 2": 1.34,
        "Corazon Empty Lot 1": 1.12,
        "Corazon Empty Lot 2": 0.98,
        "Gugo Empty Lot": 0.98,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Buguion", "population": 461, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.55, 
        "F. Mendoza Memorial Elem Sch.": 5.37, 
        "Calumpit Sports Complex": 5.55,
        "Gatbuca Basketball Court": 5.94,
        "San Miguel Meysulao High School": 10.52,
        "Doña Damiana Elem School": 10.43,
        "Danga Dike": 9.32,
        "Meysulao Multipurpose/E.C.": 7.76,
        "Calizon Dike": 5.95,
        "San Marcos Elem. Sch.": 2.31,
        "San Marcos National H.S.": 2.80,
        "GMA Kapuso E.C.": 0.16,
        "NV9 Multi-Purpose": 4.45,
        "Frances E.C.": 5.94,
        "Balungao E.C.": 5.45,
        "Gugo E.C.": 5.96,
        "San Marcos E.C.": 2.18,
        "San Jose E.C.": 10.78,
        "MEYTO Multi-Purpose/ E.C.": 10.79,
        "Barangay Hall Bulusan": 8.01,
        "Brgy. Hall Sta. Lucia": 8.34,
        "Mun. Covered Court": 5.19,
        "Pio Cruzcosa Empty Lot": 2.36,
        "Palimbang Empty Lot": 4.61,
        "Iba O'Este Empty Lot 1": 5.88,
        "Iba O'Este Empty Lot 2": 5.43,
        "Caniogan Empty Lot": 5.43,
        "Iba O'Este Empty Lot 3": 5.47,
        "Iba O'Este Empty Lot 4": 5.61,
        "Caniogan Empty Lot 2": 5.61,
        "Corazon Empty Lot 1": 5.83,
        "Corazon Empty Lot 2": 5.98,
        "Gugo Empty Lot": 5.98,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Bulusan", "population": 313, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.98, 
        "F. Mendoza Memorial Elem Sch.": 2.89, 
        "Calumpit Sports Complex": 2.98,
        "Gatbuca Basketball Court": 3.22,
        "San Miguel Meysulao High School": 7.79,
        "Doña Damiana Elem School": 7.70,
        "Danga Dike": 6.60,
        "Meysulao Multipurpose/E.C.": 0.57,
        "Calizon Dike": 1.38,
        "San Marcos Elem. Sch.": 4.91,
        "San Marcos National H.S.": 5.02,
        "GMA Kapuso E.C.": 7.25,
        "NV9 Multi-Purpose": 4.92,
        "Frances E.C.": 3.22,
        "Balungao E.C.": 1.98,
        "Gugo E.C.": 1.82,
        "San Marcos E.C.": 5.00,
        "San Jose E.C.": 3.59,
        "MEYTO Multi-Purpose/ E.C.": 3.60,
        "Barangay Hall Bulusan": 0.82,
        "Brgy. Hall Sta. Lucia": 1.15,
        "Mun. Covered Court": 2.37,
        "Pio Cruzcosa Empty Lot": 6.77,
        "Palimbang Empty Lot": 4.08,
        "Iba O'Este Empty Lot 1": 4.18,
        "Iba O'Este Empty Lot 2": 3.26,
        "Caniogan Empty Lot": 3.26,
        "Iba O'Este Empty Lot 3": 3.22,
        "Iba O'Este Empty Lot 4": 3.15,
        "Caniogan Empty Lot 2": 3.15,
        "Corazon Empty Lot 1": 2.93,
        "Corazon Empty Lot 2": 2.78,
        "Gugo Empty Lot": 2.78,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Calizon", "population": 267, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.97, 
        "F. Mendoza Memorial Elem Sch.": 1.87, 
        "Calumpit Sports Complex": 1.97,
        "Gatbuca Basketball Court": 2.20,
        "San Miguel Meysulao High School": 6.78,
        "Doña Damiana Elem School": 6.69,
        "Danga Dike": 5.58,
        "Meysulao Multipurpose/E.C.": 1.58,
        "Calizon Dike": 0.36,
        "San Marcos Elem. Sch.": 3.90,
        "San Marcos National H.S.": 4.01,
        "GMA Kapuso E.C.": 6.24,
        "NV9 Multi-Purpose": 3.91,
        "Frances E.C.": 2.20,
        "Balungao E.C.": 0.96,
        "Gugo E.C.": 1.37,
        "San Marcos E.C.": 3.98,
        "San Jose E.C.": 4.60,
        "MEYTO Multi-Purpose/ E.C.": 4.61,
        "Barangay Hall Bulusan": 1.84,
        "Brgy. Hall Sta. Lucia": 2.17,
        "Mun. Covered Court": 1.36,
        "Pio Cruzcosa Empty Lot": 5.76,
        "Palimbang Empty Lot": 3.07,
        "Iba O'Este Empty Lot 1": 3.17,
        "Iba O'Este Empty Lot 2": 3.25,
        "Caniogan Empty Lot": 2.25,
        "Iba O'Este Empty Lot 3": 2.21,
        "Iba O'Este Empty Lot 4": 2.13,
        "Caniogan Empty Lot 2": 2.13,
        "Corazon Empty Lot 1": 1.91,
        "Corazon Empty Lot 2": 1.77,
        "Gugo Empty Lot": 1.77,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.69
    }},
    {"name": "Calumpang", "population": 423, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.84, 
        "F. Mendoza Memorial Elem Sch.": 4.66, 
        "Calumpit Sports Complex": 4.84,
        "Gatbuca Basketball Court": 5.23,
        "San Miguel Meysulao High School": 9.81,
        "Doña Damiana Elem School": 9.72,
        "Danga Dike": 8.61,
        "Meysulao Multipurpose/E.C.": 7.05,
        "Calizon Dike": 5.24,
        "San Marcos Elem. Sch.": 1.80,
        "San Marcos National H.S.": 1.45,
        "GMA Kapuso E.C.": 3.85,
        "NV9 Multi-Purpose": 3.74,
        "Frances E.C.": 5.23,
        "Balungao E.C.": 4.73,
        "Gugo E.C.": 5.25,
        "San Marcos E.C.": 1.84,
        "San Jose E.C.": 10.07,
        "MEYTO Multi-Purpose/ E.C.": 10.07,
        "Barangay Hall Bulusan": 7.30,
        "Brgy. Hall Sta. Lucia": 7.63,
        "Mun. Covered Court": 4.48,
        "Pio Cruzcosa Empty Lot": 1.16,
        "Palimbang Empty Lot": 2.4,
        "Iba O'Este Empty Lot 1": 3.66,
        "Iba O'Este Empty Lot 2": 3.22,
        "Caniogan Empty Lot": 3.22,
        "Iba O'Este Empty Lot 3": 3.26,
        "Iba O'Este Empty Lot 4": 3.39,
        "Caniogan Empty Lot 2": 3.39,
        "Corazon Empty Lot 1": 3.61,
        "Corazon Empty Lot 2": 3.76,
        "Gugo Empty Lot": 3.76,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Caniogan", "population": 542, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.79, 
        "F. Mendoza Memorial Elem Sch.": 1.50, 
        "Calumpit Sports Complex": 1.79,
        "Gatbuca Basketball Court": 2.46,
        "San Miguel Meysulao High School": 7.03,
        "Doña Damiana Elem School": 6.94,
        "Danga Dike": 5.84,
        "Meysulao Multipurpose/E.C.": 4.40,
        "Calizon Dike": 2.53,
        "San Marcos Elem. Sch.": 1.59,
        "San Marcos National H.S.": 1.70,
        "GMA Kapuso E.C.": 3.93,
        "NV9 Multi-Purpose": 1.70,
        "Frances E.C.": 2.46,
        "Balungao E.C.": 1.99,
        "Gugo E.C.": 2.86,
        "San Marcos E.C.": 1.67,
        "San Jose E.C.": 7.42,
        "MEYTO Multi-Purpose/ E.C.": 7.43,
        "Barangay Hall Bulusan": 4.66,
        "Brgy. Hall Sta. Lucia": 4.99,
        "Mun. Covered Court": 1.74,
        "Pio Cruzcosa Empty Lot": 3.45,
        "Palimbang Empty Lot": 0.76,
        "Iba O'Este Empty Lot 1":0.51,
        "Iba O'Este Empty Lot 2": 1.01,
        "Caniogan Empty Lot": 1.01,
        "Iba O'Este Empty Lot 3": 0.97,
        "Iba O'Este Empty Lot 4": 0.83,
        "Caniogan Empty Lot 2": 0.83,
        "Corazon Empty Lot 1": 0.91,
        "Corazon Empty Lot 2": 1.05,
        "Gugo Empty Lot": 1.05,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Corazon", "population": 261, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.79, 
        "F. Mendoza Memorial Elem Sch.": 0.50, 
        "Calumpit Sports Complex": 0.79,
        "Gatbuca Basketball Court": 1.45,
        "San Miguel Meysulao High School": 6.03,
        "Doña Damiana Elem School": 5.94,
        "Danga Dike": 4.83,
        "Meysulao Multipurpose/E.C.": 3.46,
        "Calizon Dike": 1.58,
        "San Marcos Elem. Sch.": 2.64,
        "San Marcos National H.S.": 2.75,
        "GMA Kapuso E.C.": 4.97,
        "NV9 Multi-Purpose": 2.65,
        "Frances E.C.": 1.45,
        "Balungao E.C.": 0.96,
        "Gugo E.C.": 2.84,
        "San Marcos E.C.": 2.72,
        "San Jose E.C.": 6.48,
        "MEYTO Multi-Purpose/ E.C.": 6.49,
        "Barangay Hall Bulusan": 3.71,
        "Brgy. Hall Sta. Lucia": 4.04,
        "Mun. Covered Court": 0.71,
        "Pio Cruzcosa Empty Lot": 4.49,
        "Palimbang Empty Lot": 1.8,
        "Iba O'Este Empty Lot 1": 1.72,
        "Iba O'Este Empty Lot 2": 0.98,
        "Caniogan Empty Lot": 0.98,
        "Iba O'Este Empty Lot 3": 0.95,
        "Iba O'Este Empty Lot 4": 0.81,
        "Caniogan Empty Lot 2": 0.81,
        "Corazon Empty Lot 1": 0.59,
        "Corazon Empty Lot 2": 0.44,
        "Gugo Empty Lot": 0.44,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Frances", "population": 736, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.08, 
        "F. Mendoza Memorial Elem Sch.": 2.19, 
        "Calumpit Sports Complex": 2.08,
        "Gatbuca Basketball Court": 1.91,
        "San Miguel Meysulao High School": 5.96,
        "Doña Damiana Elem School": 5.87,
        "Danga Dike": 4.77,
        "Meysulao Multipurpose/E.C.": 4.98,
        "Calizon Dike": 3.10,
        "San Marcos Elem. Sch.": 4.86,
        "San Marcos National H.S.": 4.97,
        "GMA Kapuso E.C.": 7.19,
        "NV9 Multi-Purpose": 4.87,
        "Frances E.C.": 1.18,
        "Balungao E.C.": 2.65,
        "Gugo E.C.": 4.76,
        "San Marcos E.C.": 4.94,
        "San Jose E.C.": 8.00,
        "MEYTO Multi-Purpose/ E.C.": 8.00,
        "Barangay Hall Bulusan": 5.21,
        "Brgy. Hall Sta. Lucia": 5.56,
        "Mun. Covered Court": 2.39,
        "Pio Cruzcosa Empty Lot": 6.71,
        "Palimbang Empty Lot": 4.02,
        "Iba O'Este Empty Lot 1": 4.06,
        "Iba O'Este Empty Lot 2": 3.02,
        "Caniogan Empty Lot": 3.02,
        "Iba O'Este Empty Lot 3": 3.17,
        "Iba O'Este Empty Lot 4": 3.03,
        "Caniogan Empty Lot 2": 3.03,
        "Corazon Empty Lot 1": 2.81,
        "Corazon Empty Lot 2": 2.66,
        "Gugo Empty Lot": 2.66,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.66
    }},
    {"name": "Gatbuca", "population": 767, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.94, 
        "F. Mendoza Memorial Elem Sch.": 1.05, 
        "Calumpit Sports Complex": 0.94,
        "Gatbuca Basketball Court": 0.69,
        "San Miguel Meysulao High School": 5.26,
        "Doña Damiana Elem School": 5.18,
        "Danga Dike": 4.07,
        "Meysulao Multipurpose/E.C.": 3.83,
        "Calizon Dike": 1.95,
        "San Marcos Elem. Sch.": 3.71,
        "San Marcos National H.S.": 3.82,
        "GMA Kapuso E.C.": 6.05,
        "NV9 Multi-Purpose": 3.72,
        "Frances E.C.": 0.76,
        "Balungao E.C.": 1.51,
        "Gugo E.C.": 3.62,
        "San Marcos E.C.": 3.80,
        "San Jose E.C.": 6.85,
        "MEYTO Multi-Purpose/ E.C.": 6.86,
        "Barangay Hall Bulusan": 4.06,
        "Brgy. Hall Sta. Lucia": 4.42,
        "Mun. Covered Court": 1.25,
        "Pio Cruzcosa Empty Lot": 5.57,
        "Palimbang Empty Lot": 2.88,
        "Iba O'Este Empty Lot 1": 2.91,
        "Iba O'Este Empty Lot 2": 2.06,
        "Caniogan Empty Lot": 2.06,
        "Iba O'Este Empty Lot 3": 2.02,
        "Iba O'Este Empty Lot 4": 1.88,
        "Caniogan Empty Lot 2": 1.88,
        "Corazon Empty Lot 1": 1.66,
        "Corazon Empty Lot 2": 1.52,
        "Gugo Empty Lot": 1.52,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Gugo", "population": 236, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.34, 
        "F. Mendoza Memorial Elem Sch.": 3.25, 
        "Calumpit Sports Complex": 3.34,
        "Gatbuca Basketball Court": 3.58,
        "San Miguel Meysulao High School": 8.15,
        "Doña Damiana Elem School": 8.06,
        "Danga Dike": 6.96,
        "Meysulao Multipurpose/E.C.": 2.40,
        "Calizon Dike": 1.74,
        "San Marcos Elem. Sch.": 3.69,
        "San Marcos National H.S.": 3.80,
        "GMA Kapuso E.C.": 6.03,
        "NV9 Multi-Purpose": 3.70,
        "Frances E.C.": 3.58,
        "Balungao E.C.": 2.34,
        "Gugo E.C.": 0,
        "San Marcos E.C.": 3.78,
        "San Jose E.C.": 5.40,
        "MEYTO Multi-Purpose/ E.C.": 5.41,
        "Barangay Hall Bulusan": 2.65,
        "Brgy. Hall Sta. Lucia": 2.97,
        "Mun. Covered Court": 2.73,
        "Pio Cruzcosa Empty Lot": 5.55,
        "Palimbang Empty Lot": 2.86,
        "Iba O'Este Empty Lot 1": 3.21,
        "Iba O'Este Empty Lot 2": 2.04,
        "Caniogan Empty Lot": 2.04,
        "Iba O'Este Empty Lot 3": 2,
        "Iba O'Este Empty Lot 4": 2.03,
        "Caniogan Empty Lot 2": 2.03,
        "Corazon Empty Lot 1": 2.25,
        "Corazon Empty Lot 2": 2.4,
        "Gugo Empty Lot": 2.4,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Iba Este", "population": 500, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.84, 
        "F. Mendoza Memorial Elem Sch.": 3.65, 
        "Calumpit Sports Complex": 3.84,
        "Gatbuca Basketball Court": 4.23,
        "San Miguel Meysulao High School": 8.80,
        "Doña Damiana Elem School": 8.72,
        "Danga Dike": 7.61,
        "Meysulao Multipurpose/E.C.": 6.05,
        "Calizon Dike": 4.23,
        "San Marcos Elem. Sch.": 2.25,
        "San Marcos National H.S.": 2.36,
        "GMA Kapuso E.C.": 4.59,
        "NV9 Multi-Purpose": 2.73,
        "Frances E.C.": 4.23,
        "Balungao E.C.": 3.73,
        "Gugo E.C.": 4.25,
        "San Marcos E.C.": 2.34,
        "San Jose E.C.": 9.07,
        "MEYTO Multi-Purpose/ E.C.": 9.07,
        "Barangay Hall Bulusan": 6.30,
        "Brgy. Hall Sta. Lucia": 6.63,
        "Mun. Covered Court": 3.48,
        "Pio Cruzcosa Empty Lot": 4.11,
        "Palimbang Empty Lot": 1.42,
        "Iba O'Este Empty Lot 1": 2.66,
        "Iba O'Este Empty Lot 2": 2.22,
        "Caniogan Empty Lot": 2.22,
        "Iba O'Este Empty Lot 3": 2.25,
        "Iba O'Este Empty Lot 4": 2.39,
        "Caniogan Empty Lot 2": 2.39,
        "Corazon Empty Lot 1": 2.61,
        "Corazon Empty Lot 2": 2.76,
        "Gugo Empty Lot": 2.76,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.66
    }},
    {"name": "Iba O'Este", "population": 1691, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.60, 
        "F. Mendoza Memorial Elem Sch.": 3.43, 
        "Calumpit Sports Complex": 3.60,
        "Gatbuca Basketball Court": 3.99,
        "San Miguel Meysulao High School": 8.56,
        "Doña Damiana Elem School": 8.48,
        "Danga Dike": 7.37,
        "Meysulao Multipurpose/E.C.": 5.81,
        "Calizon Dike": 3.99,
        "San Marcos Elem. Sch.": 2.48,
        "San Marcos National H.S.": 2.60,
        "GMA Kapuso E.C.": 4.82,
        "NV9 Multi-Purpose": 0.98,
        "Frances E.C.": 3.99,
        "Balungao E.C.": 3.49,
        "Gugo E.C.": 4.01,
        "San Marcos E.C.": 2.57,
        "San Jose E.C.": 8.83,
        "MEYTO Multi-Purpose/ E.C.": 8.83,
        "Barangay Hall Bulusan": 6.06,
        "Brgy. Hall Sta. Lucia": 6.39,
        "Mun. Covered Court": 3.23,
        "Pio Cruzcosa Empty Lot": 4.34,
        "Palimbang Empty Lot": 1.65,
        "Iba O'Este Empty Lot 1": 2.52,
        "Iba O'Este Empty Lot 2": 1.98,
        "Caniogan Empty Lot": 1.98,
        "Iba O'Este Empty Lot 3": 2.01,
        "Iba O'Este Empty Lot 4": 2.15,
        "Caniogan Empty Lot 2": 2.15,
        "Corazon Empty Lot 1": 2.37,
        "Corazon Empty Lot 2": 2.52,
        "Gugo Empty Lot": 2.52,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.66
    }},
    {"name": "Longos", "population": 512, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 6.14, 
        "F. Mendoza Memorial Elem Sch.": 5.96, 
        "Calumpit Sports Complex": 6.14,
        "Gatbuca Basketball Court": 6.53,
        "San Miguel Meysulao High School": 11.11,
        "Doña Damiana Elem School": 11.02,
        "Danga Dike": 9.91,
        "Meysulao Multipurpose/E.C.": 8.35,
        "Calizon Dike": 6.54,
        "San Marcos Elem. Sch.": 3.11,
        "San Marcos National H.S.": 2.75,
        "GMA Kapuso E.C.": 5.16,
        "NV9 Multi-Purpose": 5.04,
        "Frances E.C.": 6.54,
        "Balungao E.C.": 6.04,
        "Gugo E.C.": 6.55,
        "San Marcos E.C.": 3.14,
        "San Jose E.C.": 11.37,
        "MEYTO Multi-Purpose/ E.C.": 11.38,
        "Barangay Hall Bulusan": 8.60,
        "Brgy. Hall Sta. Lucia": 8.93,
        "Mun. Covered Court": 5.78,
        "Pio Cruzcosa Empty Lot": 1.91,
        "Palimbang Empty Lot": 3.7,
        "Iba O'Este Empty Lot 1": 4.96,
        "Iba O'Este Empty Lot 2": 4.52,
        "Caniogan Empty Lot": 4.52,
        "Iba O'Este Empty Lot 3": 4.56,
        "Iba O'Este Empty Lot 4": 4.7,
        "Caniogan Empty Lot 2": 4.7,
        "Corazon Empty Lot 1": 4.92,
        "Corazon Empty Lot 2": 5.06,
        "Gugo Empty Lot": 5.06,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Meysulao", "population": 514, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.56, 
        "F. Mendoza Memorial Elem Sch.": 3.46, 
        "Calumpit Sports Complex": 3.56,
        "Gatbuca Basketball Court": 3.79,
        "San Miguel Meysulao High School": 8.37,
        "Doña Damiana Elem School": 8.28,
        "Danga Dike": 7.17,
        "Meysulao Multipurpose/E.C.": 0,
        "Calizon Dike": 1.95,
        "San Marcos Elem. Sch.": 5.49,
        "San Marcos National H.S.": 5.60,
        "GMA Kapuso E.C.": 7.83,
        "NV9 Multi-Purpose": 5.50,
        "Frances E.C.": 3.79,
        "Balungao E.C.": 2.55,
        "Gugo E.C.": 2.40,
        "San Marcos E.C.": 5.57,
        "San Jose E.C.": 3.34,
        "MEYTO Multi-Purpose/ E.C.": 3.34,
        "Barangay Hall Bulusan": 0.25,
        "Brgy. Hall Sta. Lucia": 1.02,
        "Mun. Covered Court": 2.95,
        "Pio Cruzcosa Empty Lot": 7.35,
        "Palimbang Empty Lot": 4.66,
        "Iba O'Este Empty Lot 1": 4.76,
        "Iba O'Este Empty Lot 2": 3.84,
        "Caniogan Empty Lot": 3.84,
        "Iba O'Este Empty Lot 3": 3.8,
        "Iba O'Este Empty Lot 4": 3.72,
        "Caniogan Empty Lot 2": 3.72,
        "Corazon Empty Lot 1": 3.5,
        "Corazon Empty Lot 2": 3.36,
        "Gugo Empty Lot": 3.36,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.65
    }},
    {"name": "Meyto", "population": 351, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 6.49, 
        "F. Mendoza Memorial Elem Sch.": 6.40, 
        "Calumpit Sports Complex": 6.49,
        "Gatbuca Basketball Court": 6.73,
        "San Miguel Meysulao High School": 11.30,
        "Doña Damiana Elem School": 11.21,
        "Danga Dike": 10.11,
        "Meysulao Multipurpose/E.C.": 3.25,
        "Calizon Dike": 4.89,
        "San Marcos Elem. Sch.": 8.42,
        "San Marcos National H.S.": 8.54,
        "GMA Kapuso E.C.": 10.76,
        "NV9 Multi-Purpose": 8.43,
        "Frances E.C.": 6.73,
        "Balungao E.C.": 5.49,
        "Gugo E.C.": 5.32,
        "San Marcos E.C.": 8.51,
        "San Jose E.C.": 0.67,
        "MEYTO Multi-Purpose/ E.C.": 0.08,
        "Barangay Hall Bulusan": 3.50,
        "Brgy. Hall Sta. Lucia": 2.35,
        "Mun. Covered Court": 5.88,
        "Pio Cruzcosa Empty Lot": 10.28,
        "Palimbang Empty Lot": 7.59,
        "Iba O'Este Empty Lot 1": 7.69,
        "Iba O'Este Empty Lot 2": 6.77,
        "Caniogan Empty Lot": 6.77,
        "Iba O'Este Empty Lot 3": 6.73,
        "Iba O'Este Empty Lot 4": 6.66,
        "Caniogan Empty Lot 2": 6.66,
        "Corazon Empty Lot 1": 6.44,
        "Corazon Empty Lot 2": 6.3,
        "Gugo Empty Lot": 6.3,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.66
    }},
    {"name": "Palimbang", "population": 203, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.92, 
        "F. Mendoza Memorial Elem Sch.": 2.74, 
        "Calumpit Sports Complex": 2.92,
        "Gatbuca Basketball Court": 3.31,
        "San Miguel Meysulao High School": 7.89,
        "Doña Damiana Elem School": 7.80,
        "Danga Dike": 6.69,
        "Meysulao Multipurpose/E.C.": 5.13,
        "Calizon Dike": 3.32,
        "San Marcos Elem. Sch.": 0.35,
        "San Marcos National H.S.": 0.72,
        "GMA Kapuso E.C.": 2.73,
        "NV9 Multi-Purpose": 1.82,
        "Frances E.C.": 3.31,
        "Balungao E.C.": 2.81,
        "Gugo E.C.": 3.33,
        "San Marcos E.C.": 0.48,
        "San Jose E.C.": 8.15,
        "MEYTO Multi-Purpose/ E.C.": 5.15,
        "Barangay Hall Bulusan": 5.38,
        "Brgy. Hall Sta. Lucia": 5.71,
        "Mun. Covered Court": 2.56,
        "Pio Cruzcosa Empty Lot": 2.46,
        "Palimbang Empty Lot": 0.48,
        "Iba O'Este Empty Lot 1": 1.74,
        "Iba O'Este Empty Lot 2": 1.3,
        "Caniogan Empty Lot": 1.3,
        "Iba O'Este Empty Lot 3": 1.34,
        "Iba O'Este Empty Lot 4": 1.47,
        "Caniogan Empty Lot 2": 1.47,
        "Corazon Empty Lot 1": 1.7,
        "Corazon Empty Lot 2": 1.84,
        "Gugo Empty Lot": 1.84,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Panducot", "population": 211, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 7.71, 
        "F. Mendoza Memorial Elem Sch.": 7.62, 
        "Calumpit Sports Complex": 7.71,
        "Gatbuca Basketball Court": 7.95,
        "San Miguel Meysulao High School": 12.52,
        "Doña Damiana Elem School": 12.43,
        "Danga Dike": 11.33,
        "Meysulao Multipurpose/E.C.": 4.47,
        "Calizon Dike": 6.11,
        "San Marcos Elem. Sch.": 9.64,
        "San Marcos National H.S.": 9.75,
        "GMA Kapuso E.C.": 11.98,
        "NV9 Multi-Purpose": 9.65,
        "Frances E.C.": 7.95,
        "Balungao E.C.": 6.71,
        "Gugo E.C.": 6.54,
        "San Marcos E.C.": 9.73,
        "San Jose E.C.": 1.89,
        "MEYTO Multi-Purpose/ E.C.": 1.37,
        "Barangay Hall Bulusan": 4.72,
        "Brgy. Hall Sta. Lucia": 3.57,
        "Mun. Covered Court": 7.10,
        "Pio Cruzcosa Empty Lot": 11.5,
        "Palimbang Empty Lot": 8.81,
        "Iba O'Este Empty Lot 1": 8.91,
        "Iba O'Este Empty Lot 2": 7.99,
        "Caniogan Empty Lot": 7.99,
        "Iba O'Este Empty Lot 3": 7.95,
        "Iba O'Este Empty Lot 4": 7.88,
        "Caniogan Empty Lot 2": 7.88,
        "Corazon Empty Lot 1": 7.66,
        "Corazon Empty Lot 2": 7.51,
        "Gugo Empty Lot": 7.51,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.68
    }},
        {"name": "Pio Cruzcosa", "population": 560, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.42, 
        "F. Mendoza Memorial Elem Sch.": 4.23, 
        "Calumpit Sports Complex": 4.42,
        "Gatbuca Basketball Court": 4.81,
        "San Miguel Meysulao High School": 9.38,
        "Doña Damiana Elem School": 9.30,
        "Danga Dike": 8.19,
        "Meysulao Multipurpose/E.C.": 6.63,
        "Calizon Dike": 4.81,
        "San Marcos Elem. Sch.": 1.38,
        "San Marcos National H.S.": 1.17,
        "GMA Kapuso E.C.": 3.41,
        "NV9 Multi-Purpose": 3.31,
        "Frances E.C.": 4.81,
        "Balungao E.C.": 4.31,
        "Gugo E.C.": 4.83,
        "San Marcos E.C.": 1.39,
        "San Jose E.C.": 9.65,
        "MEYTO Multi-Purpose/ E.C.": 9.65,
        "Barangay Hall Bulusan": 6.88,
        "Brgy. Hall Sta. Lucia": 7.21,
        "Mun. Covered Court": 4.06,
        "Pio Cruzcosa Empty Lot": 0.91,
        "Palimbang Empty Lot": 2.07,
        "Iba O'Este Empty Lot 1": 3.34,
        "Iba O'Este Empty Lot 2": 2.89,
        "Caniogan Empty Lot": 2.89,
        "Iba O'Este Empty Lot 3": 2.93,
        "Iba O'Este Empty Lot 4": 3.07,
        "Caniogan Empty Lot 2": 3.07,
        "Corazon Empty Lot 1": 3.29,
        "Corazon Empty Lot 2": 3.43,
        "Gugo Empty Lot": 3.43,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Poblacion", "population": 215, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.47, 
        "F. Mendoza Memorial Elem Sch.": 0.29, 
        "Calumpit Sports Complex": 0.47,
        "Gatbuca Basketball Court": 0.98,
        "San Miguel Meysulao High School": 5.56,
        "Doña Damiana Elem School": 5.47,
        "Danga Dike": 4.36,
        "Meysulao Multipurpose/E.C.": 3.17,
        "Calizon Dike": 1.29,
        "San Marcos Elem. Sch.": 2.82,
        "San Marcos National H.S.": 2.93,
        "GMA Kapuso E.C.": 5.16,
        "NV9 Multi-Purpose": 2.83,
        "Frances E.C.": 0.98,
        "Balungao E.C.": 0.61,
        "Gugo E.C.": 2.96,
        "San Marcos E.C.": 2.91,
        "San Jose E.C.": 6.19,
        "MEYTO Multi-Purpose/ E.C.": 6.20,
        "Barangay Hall Bulusan": 3.42,
        "Brgy. Hall Sta. Lucia": 3.75,
        "Mun. Covered Court": 0.36,
        "Pio Cruzcosa Empty Lot": 4.68,
        "Palimbang Empty Lot": 1.99,
        "Iba O'Este Empty Lot 1": 1.98,
        "Iba O'Este Empty Lot 2": 1.17,
        "Caniogan Empty Lot": 1.17,
        "Iba O'Este Empty Lot 3": 1.13,
        "Iba O'Este Empty Lot 4": 0.99,
        "Caniogan Empty Lot 2": 0.99,
        "Corazon Empty Lot 1": 0.77,
        "Corazon Empty Lot 2": 0.63,
        "Gugo Empty Lot": 0.63,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.68
    }},
    {"name": "Pungo", "population": 1144, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.94, 
        "F. Mendoza Memorial Elem Sch.": 3.66, 
        "Calumpit Sports Complex": 3.94,
        "Gatbuca Basketball Court": 4.61,
        "San Miguel Meysulao High School": 9.19,
        "Doña Damiana Elem School": 9.10,
        "Danga Dike": 7.99,
        "Meysulao Multipurpose/E.C.": 6.56,
        "Calizon Dike": 5.68,
        "San Marcos Elem. Sch.": 3.74,
        "San Marcos National H.S.": 3.85,
        "GMA Kapuso E.C.": 6.08,
        "NV9 Multi-Purpose": 3.85,
        "Frances E.C.": 4.61,
        "Balungao E.C.": 4.15,
        "Gugo E.C.": 5.01,
        "San Marcos E.C.": 3.83,
        "San Jose E.C.": 9.58,
        "MEYTO Multi-Purpose/ E.C.": 9.58,
        "Barangay Hall Bulusan": 6.81,
        "Brgy. Hall Sta. Lucia": 7.14,
        "Mun. Covered Court": 3.89,
        "Pio Cruzcosa Empty Lot": 5.6,
        "Palimbang Empty Lot": 2.91,
        "Iba O'Este Empty Lot 1": 2.66,
        "Iba O'Este Empty Lot 2": 3.16,
        "Caniogan Empty Lot": 3.16,
        "Iba O'Este Empty Lot 3": 3.13,
        "Iba O'Este Empty Lot 4": 2.99,
        "Caniogan Empty Lot 2": 2.99,
        "Corazon Empty Lot 1": 3.06,
        "Corazon Empty Lot 2": 3.2,
        "Gugo Empty Lot": 3.2,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "San Jose", "population": 680, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 7.59, 
        "F. Mendoza Memorial Elem Sch.": 7.49, 
        "Calumpit Sports Complex": 7.59,
        "Gatbuca Basketball Court": 7.82,
        "San Miguel Meysulao High School": 12.40,
        "Doña Damiana Elem School": 12.31,
        "Danga Dike": 11.20,
        "Meysulao Multipurpose/E.C.": 4.35,
        "Calizon Dike": 5.98,
        "San Marcos Elem. Sch.": 8.13,
        "San Marcos National H.S.": 8.24,
        "GMA Kapuso E.C.": 10.47,
        "NV9 Multi-Purpose": 8.14,
        "Frances E.C.": 7.82,
        "Balungao E.C.": 6.58,
        "Gugo E.C.": 4.43,
        "San Marcos E.C.": 8.22,
        "San Jose E.C.": 1.34,
        "MEYTO Multi-Purpose/ E.C.": 1.77,
        "Barangay Hall Bulusan": 4.60,
        "Brgy. Hall Sta. Lucia": 3.44,
        "Mun. Covered Court": 6.97,
        "Pio Cruzcosa Empty Lot": 9.99,
        "Palimbang Empty Lot": 7.3,
        "Iba O'Este Empty Lot 1": 7.65,
        "Iba O'Este Empty Lot 2": 6.48,
        "Caniogan Empty Lot": 6.48,
        "Iba O'Este Empty Lot 3": 6.44,
        "Iba O'Este Empty Lot 4": 6.47,
        "Caniogan Empty Lot 2": 6.47,
        "Corazon Empty Lot 1": 6.69,
        "Corazon Empty Lot 2": 6.84,
        "Gugo Empty Lot": 6.84,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "San Marcos", "population": 321, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.37, 
        "F. Mendoza Memorial Elem Sch.": 3.18, 
        "Calumpit Sports Complex": 3.37,
        "Gatbuca Basketball Court": 3.76,
        "San Miguel Meysulao High School": 8.33,
        "Doña Damiana Elem School": 8.24,
        "Danga Dike": 7.14,
        "Meysulao Multipurpose/E.C.": 5.57,
        "Calizon Dike": 3.76,
        "San Marcos Elem. Sch.": 0.12,
        "San Marcos National H.S.": 0.65,
        "GMA Kapuso E.C.": 2.25,
        "NV9 Multi-Purpose": 2.26,
        "Frances E.C.": 3.76,
        "Balungao E.C.": 3.26,
        "Gugo E.C.": 3.78,
        "San Marcos E.C.": 0,
        "San Jose E.C.": 8.59,
        "MEYTO Multi-Purpose/ E.C.": 8.60,
        "Barangay Hall Bulusan": 5.83,
        "Brgy. Hall Sta. Lucia": 6.16,
        "Mun. Covered Court": 3.00,
        "Pio Cruzcosa Empty Lot": 2.11,
        "Palimbang Empty Lot": 0.95,
        "Iba O'Este Empty Lot 1": 2.19,
        "Iba O'Este Empty Lot 2": 1.74,
        "Caniogan Empty Lot": 1.74,
        "Iba O'Este Empty Lot 3": 1.78,
        "Iba O'Este Empty Lot 4": 1.92,
        "Caniogan Empty Lot 2": 1.92,
        "Corazon Empty Lot 1": 2.14,
        "Corazon Empty Lot 2": 2.29,
        "Gugo Empty Lot": 2.29,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.66
    }},
    {"name": "San Miguel", "population": 721, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.47, 
        "F. Mendoza Memorial Elem Sch.": 5.58, 
        "Calumpit Sports Complex": 5.47,
        "Gatbuca Basketball Court": 4.91,
        "San Miguel Meysulao High School": 0,
        "Doña Damiana Elem School": 0.08,
        "Danga Dike": 2.07,
        "Meysulao Multipurpose/E.C.": 8.37,
        "Calizon Dike": 6.49,
        "San Marcos Elem. Sch.": 8.24,
        "San Marcos National H.S.": 8.36,
        "GMA Kapuso E.C.": 10.58,
        "NV9 Multi-Purpose": 8.26,
        "Frances E.C.": 5.25,
        "Balungao E.C.": 6.04,
        "Gugo E.C.": 8.15,
        "San Marcos E.C.": 8.33,
        "San Jose E.C.": 11.38,
        "MEYTO Multi-Purpose/ E.C.": 11.39,
        "Barangay Hall Bulusan": 8.60,
        "Brgy. Hall Sta. Lucia": 8.95,
        "Mun. Covered Court": 5.78,
        "Pio Cruzcosa Empty Lot": 10.1,
        "Palimbang Empty Lot": 7.41,
        "Iba O'Este Empty Lot 1": 7.45,
        "Iba O'Este Empty Lot 2": 6.59,
        "Caniogan Empty Lot": 6.59,
        "Iba O'Este Empty Lot 3": 6.56,
        "Iba O'Este Empty Lot 4": 6.42,
        "Caniogan Empty Lot 2": 6.42,
        "Corazon Empty Lot 1": 6.2,
        "Corazon Empty Lot 2": 6.05,
        "Gugo Empty Lot": 6.05,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Santa Lucia", "population": 296, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.41, 
        "F. Mendoza Memorial Elem Sch.": 4.32, 
        "Calumpit Sports Complex": 4.41,
        "Gatbuca Basketball Court": 4.65,
        "San Miguel Meysulao High School": 9.22,
        "Doña Damiana Elem School": 9.14,
        "Danga Dike": 8.03,
        "Meysulao Multipurpose/E.C.": 1.29,
        "Calizon Dike": 2.81,
        "San Marcos Elem. Sch.": 6.35,
        "San Marcos National H.S.": 6.46,
        "GMA Kapuso E.C.": 8.68,
        "NV9 Multi-Purpose": 6.36,
        "Frances E.C.": 4.65,
        "Balungao E.C.": 3.41,
        "Gugo E.C.": 3.24,
        "San Marcos E.C.": 6.43,
        "San Jose E.C.": 2.16,
        "MEYTO Multi-Purpose/ E.C.": 2.16,
        "Barangay Hall Bulusan": 1.55,
        "Brgy. Hall Sta. Lucia": 0.27,
        "Mun. Covered Court": 3.80,
        "Pio Cruzcosa Empty Lot": 8.2,
        "Palimbang Empty Lot": 5.51,
        "Iba O'Este Empty Lot 1": 5.61,
        "Iba O'Este Empty Lot 2": 4.69,
        "Caniogan Empty Lot": 4.69,
        "Iba O'Este Empty Lot 3": 4.66,
        "Iba O'Este Empty Lot 4": 4.58,
        "Caniogan Empty Lot 2": 4.58,
        "Corazon Empty Lot 1": 4.36,
        "Corazon Empty Lot 2": 4.22,
        "Gugo Empty Lot": 4.22,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
    {"name": "Santo Niño", "population": 306, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.41, 
        "F. Mendoza Memorial Elem Sch.": 2.12, 
        "Calumpit Sports Complex": 2.41,
        "Gatbuca Basketball Court": 3.08,
        "San Miguel Meysulao High School": 7.65,
        "Doña Damiana Elem School": 7.57,
        "Danga Dike": 6.46,
        "Meysulao Multipurpose/E.C.": 5.03,
        "Calizon Dike": 3.15,
        "San Marcos Elem. Sch.": 2.21,
        "San Marcos National H.S.": 2.32,
        "GMA Kapuso E.C.": 4.55,
        "NV9 Multi-Purpose": 2.32,
        "Frances E.C.": 3.08,
        "Balungao E.C.": 2.62,
        "Gugo E.C.": 3.48,
        "San Marcos E.C.": 2.30,
        "San Jose E.C.": 8.05,
        "MEYTO Multi-Purpose/ E.C.": 8.05,
        "Barangay Hall Bulusan": 5.28,
        "Brgy. Hall Sta. Lucia": 5.61,
        "Mun. Covered Court": 2.36,
        "Pio Cruzcosa Empty Lot": 4.07,
        "Palimbang Empty Lot": 1.38,
        "Iba O'Este Empty Lot 1": 1.13,
        "Iba O'Este Empty Lot 2": 1.63,
        "Caniogan Empty Lot": 1.63,
        "Iba O'Este Empty Lot 3": 1.59,
        "Iba O'Este Empty Lot 4": 1.46,
        "Caniogan Empty Lot 2": 1.46,
        "Corazon Empty Lot 1": 1.53,
        "Corazon Empty Lot 2": 1.67,
        "Gugo Empty Lot": 1.67,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.71
    }},    
    {"name": "Sapang Bayan", "population": 377, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.89, 
        "F. Mendoza Memorial Elem Sch.": 0.81, 
        "Calumpit Sports Complex": 0.89,
        "Gatbuca Basketball Court": 1.61,
        "San Miguel Meysulao High School": 6.18,
        "Doña Damiana Elem School": 6.10,
        "Danga Dike": 4.99,
        "Meysulao Multipurpose/E.C.": 4.27,
        "Calizon Dike": 2.39,
        "San Marcos Elem. Sch.": 3.91,
        "San Marcos National H.S.": 4.02,
        "GMA Kapuso E.C.": 6.25,
        "NV9 Multi-Purpose": 3.94,
        "Frances E.C.": 1.61,
        "Balungao E.C.": 1.72,
        "Gugo E.C.": 4.06,
        "San Marcos E.C.": 4.00,
        "San Jose E.C.": 7.29,
        "MEYTO Multi-Purpose/ E.C.": 7.30,
        "Barangay Hall Bulusan": 4.50,
        "Brgy. Hall Sta. Lucia": 4.85,
        "Mun. Covered Court": 1.47,
        "Pio Cruzcosa Empty Lot": 5.77,
        "Palimbang Empty Lot": 3.08,
        "Iba O'Este Empty Lot 1": 2.83,
        "Iba O'Este Empty Lot 2": 2.28,
        "Caniogan Empty Lot": 2.28,
        "Iba O'Este Empty Lot 3": 2.24,
        "Iba O'Este Empty Lot 4": 2.1,
        "Caniogan Empty Lot 2": 2.1,
        "Corazon Empty Lot 1": 1.88,
        "Corazon Empty Lot 2": 1.74,
        "Gugo Empty Lot": 1.74,}, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.64
    }},
    {"name": "Sergio Bayan", "population": 208, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.02, 
        "F. Mendoza Memorial Elem Sch.": 4.84, 
        "Calumpit Sports Complex": 5.02,
        "Gatbuca Basketball Court": 5.41,
        "San Miguel Meysulao High School": 9.99,
        "Doña Damiana Elem School": 9.90,
        "Danga Dike": 8.79,
        "Meysulao Multipurpose/E.C.": 7.23,
        "Calizon Dike": 5.42,
        "San Marcos Elem. Sch.": 1.78,
        "San Marcos National H.S.": 2.11,
        "GMA Kapuso E.C.": 0.68,
        "NV9 Multi-Purpose": 3.92,
        "Frances E.C.": 5.41,
        "Balungao E.C.": 4.92,
        "Gugo E.C.": 5.43,
        "San Marcos E.C.": 1.65,
        "San Jose E.C.": 10.25,
        "MEYTO Multi-Purpose/ E.C.": 10.26,
        "Barangay Hall Bulusan": 7.48,
        "Brgy. Hall Sta. Lucia": 7.81,
        "Mun. Covered Court": 4.66,
        "Pio Cruzcosa Empty Lot": 1.71,
        "Palimbang Empty Lot": 2.6,
        "Iba O'Este Empty Lot 1": 3.84,
        "Iba O'Este Empty Lot 2": 3.4,
        "Caniogan Empty Lot": 3.4,
        "Iba O'Este Empty Lot 3": 3.44,
        "Iba O'Este Empty Lot 4": 3.58,
        "Caniogan Empty Lot 2": 3.58,
        "Corazon Empty Lot 1": 3.8,
        "Corazon Empty Lot 2": 3.94,
        "Gugo Empty Lot": 3.94,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.64
    }},
    {"name": "Sucol", "population": 128, "maxdistance": 12, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.77, 
        "F. Mendoza Memorial Elem Sch.": 0.48, 
        "Calumpit Sports Complex": 0.77,
        "Gatbuca Basketball Court": 1.44,
        "San Miguel Meysulao High School": 6.01,
        "Doña Damiana Elem School": 5.92,
        "Danga Dike": 4.82,
        "Meysulao Multipurpose/E.C.": 3.53,
        "Calizon Dike": 1.65,
        "San Marcos Elem. Sch.": 2.61,
        "San Marcos National H.S.": 2.72,
        "GMA Kapuso E.C.": 4.95,
        "NV9 Multi-Purpose": 2.72,
        "Frances E.C.": 1.44,
        "Balungao E.C.": 0.97,
        "Gugo E.C.": 3.03,
        "San Marcos E.C.": 2.70,
        "San Jose E.C.": 6.55,
        "MEYTO Multi-Purpose/ E.C.": 6.56,
        "Barangay Hall Bulusan": 3.78,
        "Brgy. Hall Sta. Lucia": 4.11,
        "Mun. Covered Court": 0.72,
        "Pio Cruzcosa Empty Lot": 4.47,
        "Palimbang Empty Lot": 1.78,
        "Iba O'Este Empty Lot 1": 1.53,
        "Iba O'Este Empty Lot 2": 1.18,
        "Caniogan Empty Lot": 1.18,
        "Iba O'Este Empty Lot 3": 1.14,
        "Iba O'Este Empty Lot 4": 1,
        "Caniogan Empty Lot 2": 1,
        "Corazon Empty Lot 1": 0.78,
        "Corazon Empty Lot 2": 0.63,
        "Gugo Empty Lot": 0.63,
        }, 
    "portiontransfer":0.5,
    "portionwork" : {
        "Work1" : 0.67
    }},
]

# list of shelters with area1 and cost1 (area and cost as level 1 shelter), area 2 and cost2 (area and cost as level 2 shelter) 
Shelters = [
    {"name": "BMLTC Multi-Purpose Bldg and EC", "area1": 1641, "cost1": 12635700, "area2": 3282, "cost2": 98460000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0, 
        "F. Mendoza Memorial Elem Sch.": 0.28, 
        "Calumpit Sports Complex": 0,
        "Gatbuca Basketball Court": 0.90,
        "San Miguel Meysulao High School": 5.47,
        "Doña Damiana Elem School": 5.38,
        "Danga Dike": 4.28,
        "Meysulao Multipurpose/E.C.": 3.56,
        "Calizon Dike": 1.68,
        "San Marcos Elem. Sch.": 3.28,
        "San Marcos National H.S.": 3.39,
        "GMA Kapuso E.C.": 5.62,
        "NV9 Multi-Purpose": 3.29,
        "Frances E.C.": 0.90,
        "Balungao E.C.": 1.07,
        "Gugo E.C.": 3.34,
        "San Marcos E.C.": 3.37,
        "San Jose E.C.": 6.58,
        "MEYTO Multi-Purpose/ E.C.": 6.58,
        "Barangay Hall Bulusan": 3.79,
        "Brgy. Hall Sta. Lucia": 4.14,
        "Mun. Covered Court": 0.82,
        "Pio Cruzcosa Empty Lot": 5.14,
        "Palimbang Empty Lot": 2.45,
        "Iba O'Este Empty Lot 1": 2.30,
        "Iba O'Este Empty Lot 2": 1.63,
        "Caniogan Empty Lot": 1.63,
        "Iba O'Este Empty Lot 3": 1.59,
        "Iba O'Este Empty Lot 4": 1.45,
        "Caniogan Empty Lot 2": 1.45,
        "Corazon Empty Lot 1": 1.23,
        "Corazon Empty Lot 2": 1.09,
        "Gugo Empty Lot": 1.09,
    },
    "distanceswork": {
         "Work1": 3.00
    }},
    {"name": "F. Mendoza Memorial Elem Sch.", "area1": 1671, "cost1": 12866700, "area2": 3342, "cost2": 100260000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.28, 
        "F. Mendoza Memorial Elem Sch.": 0, 
        "Calumpit Sports Complex": 0.28,
        "Gatbuca Basketball Court": 1.01,
        "San Miguel Meysulao High School": 5.58,
        "Doña Damiana Elem School": 5.49,
        "Danga Dike": 4.38,
        "Meysulao Multipurpose/E.C.": 3.46,
        "Calizon Dike": 1.59,
        "San Marcos Elem. Sch.": 3.09,
        "San Marcos National H.S.": 3.21,
        "GMA Kapuso E.C.": 5.43,
        "NV9 Multi-Purpose": 3.12,
        "Frances E.C.": 1.01,
        "Balungao E.C.": 0.91,
        "Gugo E.C.":3.25,
        "San Marcos E.C.": 3.18,
        "San Jose E.C.": 6.48,
        "MEYTO Multi-Purpose/ E.C.": 6.49,
        "Barangay Hall Bulusan": 3.72,
        "Brgy. Hall Sta. Lucia": 4.05,
        "Mun. Covered Court": 0.65,
        "Pio Cruzcosa Empty Lot": 4.95,
        "Palimbang Empty Lot": 2.26,
        "Iba O'Este Empty Lot 1": 2.01,
        "Iba O'Este Empty Lot 2": 1.46,
        "Caniogan Empty Lot": 1.46,
        "Iba O'Este Empty Lot 3": 1.42,
        "Iba O'Este Empty Lot 4": 1.29,
        "Caniogan Empty Lot 2": 1.29,
        "Corazon Empty Lot 1": 1.07,
        "Corazon Empty Lot 2": 0.92,
        "Gugo Empty Lot": 0.92,
    },
    "distanceswork": {
         "Work1": 2.81
    }},
    {"name": "Calumpit Sports Complex", "area1": 947, "cost1": 7291900, "area2": 1894, "cost2": 56820000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0, 
        "F. Mendoza Memorial Elem Sch.": 0.28, 
        "Calumpit Sports Complex": 0,
        "Gatbuca Basketball Court": 0.90,
        "San Miguel Meysulao High School": 5.47,
        "Doña Damiana Elem School": 5.38,
        "Danga Dike": 4.28,
        "Meysulao Multipurpose/E.C.": 3.56,
        "Calizon Dike": 1.68,
        "San Marcos Elem. Sch.": 3.28,
        "San Marcos National H.S.": 3.39,
        "GMA Kapuso E.C.": 5.62,
        "NV9 Multi-Purpose": 3.29,
        "Frances E.C.": 0.90,
        "Balungao E.C.": 1.07,
        "Gugo E.C.": 3.34,
        "San Marcos E.C.": 3.37,
        "San Jose E.C.": 6.58,
        "MEYTO Multi-Purpose/ E.C.": 6.58,
        "Barangay Hall Bulusan": 3.79,
        "Brgy. Hall Sta. Lucia": 4.14,
        "Mun. Covered Court": 0.82,
        "Pio Cruzcosa Empty Lot": 5.14,
        "Palimbang Empty Lot": 2.45,
        "Iba O'Este Empty Lot 1": 2.30,
        "Iba O'Este Empty Lot 2": 1.63,
        "Caniogan Empty Lot": 1.63,
        "Iba O'Este Empty Lot 3": 1.59,
        "Iba O'Este Empty Lot 4": 1.45,
        "Caniogan Empty Lot 2": 1.45,
        "Corazon Empty Lot 1": 1.23,
        "Corazon Empty Lot 2": 1.09,
        "Gugo Empty Lot": 1.09,
    },
    "distanceswork": {
         "Work1": 3.00
    }},
    {"name": "Gatbuca Basketball Court", "area1": 376, "cost1": 2895200, "area2": 752, "cost2": 22560000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.90, 
        "F. Mendoza Memorial Elem Sch.": 1.01, 
        "Calumpit Sports Complex": 0.90,
        "Gatbuca Basketball Court": 0,
        "San Miguel Meysulao High School": 4.91,
        "Doña Damiana Elem School": 4.83,
        "Danga Dike": 3.72,
        "Meysulao Multipurpose/E.C.": 3.79,
        "Calizon Dike": 1.91,
        "San Marcos Elem. Sch.": 3.67,
        "San Marcos National H.S.": 3.78,
        "GMA Kapuso E.C.": 6.01,
        "NV9 Multi-Purpose": 3.68,
        "Frances E.C.": 0.72,
        "Balungao E.C.": 1.46,
        "Gugo E.C.": 3.58,
        "San Marcos E.C.": 3.76,
        "San Jose E.C.": 6.81,
        "MEYTO Multi-Purpose/ E.C.": 6.82,
        "Barangay Hall Bulusan": 4.02,
        "Brgy. Hall Sta. Lucia": 4.37,
        "Mun. Covered Court": 1.21,
        "Pio Cruzcosa Empty Lot": 5.53,
        "Palimbang Empty Lot": 2.84,
        "Iba O'Este Empty Lot 1": 2.87,
        "Iba O'Este Empty Lot 2": 2.02,
        "Caniogan Empty Lot": 2.02,
        "Iba O'Este Empty Lot 3": 1.98,
        "Iba O'Este Empty Lot 4": 1.84,
        "Caniogan Empty Lot 2": 1.84,
        "Corazon Empty Lot 1": 1.62,
        "Corazon Empty Lot 2": 1.48,
        "Gugo Empty Lot": 1.48,
    },
    "distanceswork": {
         "Work1": 3.39
    }},
        {"name": "San Miguel Meysulao High School", "area1": 3464, "cost1": 26672800, "area2": 6928, "cost2": 207840000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.47, 
        "F. Mendoza Memorial Elem Sch.": 5.58, 
        "Calumpit Sports Complex": 5.47,
        "Gatbuca Basketball Court": 4.91,
        "San Miguel Meysulao High School": 0,
        "Doña Damiana Elem School": 0.08,
        "Danga Dike": 2.0,
        "Meysulao Multipurpose/E.C.": 8.37,
        "Calizon Dike": 6.49,
        "San Marcos Elem. Sch.": 8.24,
        "San Marcos National H.S.": 8.36,
        "GMA Kapuso E.C.": 10.58,
        "NV9 Multi-Purpose": 8.26,
        "Frances E.C.": 5.25,
        "Balungao E.C.": 6.04,
        "Gugo E.C.": 8.15,
        "San Marcos E.C.": 8.33,
        "San Jose E.C.": 11.38,
        "MEYTO Multi-Purpose/ E.C.": 11.39,
        "Barangay Hall Bulusan": 8.60,
        "Brgy. Hall Sta. Lucia": 8.95,
        "Mun. Covered Court": 5.78,
        "Pio Cruzcosa Empty Lot": 10.10,
        "Palimbang Empty Lot": 7.41,
        "Iba O'Este Empty Lot 1": 7.45,
        "Iba O'Este Empty Lot 2": 6.59,
        "Caniogan Empty Lot": 6.59,
        "Iba O'Este Empty Lot 3": 6.55,
        "Iba O'Este Empty Lot 4": 6.42,
        "Caniogan Empty Lot 2": 6.42,
        "Corazon Empty Lot 1": 6.19,
        "Corazon Empty Lot 2": 6.05,
        "Gugo Empty Lot": 6.05,
    },
    "distanceswork": {
         "Work1": 7.96
    }},
    {"name": "Doña Damiana Elem School", "area1": 3135, "cost1": 24139500, "area2": 6270, "cost2": 188100000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.38, 
        "F. Mendoza Memorial Elem Sch.": 5.49, 
        "Calumpit Sports Complex": 5.38,
        "Gatbuca Basketball Court": 4.83,
        "San Miguel Meysulao High School": 0.08,
        "Doña Damiana Elem School": 0,
        "Danga Dike": 1.98,
        "Meysulao Multipurpose/E.C.": 8.28,
        "Calizon Dike": 6.40,
        "San Marcos Elem. Sch.": 8.16,
        "San Marcos National H.S.": 8.27,
        "GMA Kapuso E.C.": 10.49,
        "NV9 Multi-Purpose": 8.17,
        "Frances E.C.": 5.16,
        "Balungao E.C.": 5.95,
        "Gugo E.C.": 8.06,
        "San Marcos E.C.": 8.24,
        "San Jose E.C.": 11.30,
        "MEYTO Multi-Purpose/ E.C.": 11.30,
        "Barangay Hall Bulusan": 8.51,
        "Brgy. Hall Sta. Lucia": 8.86,
        "Mun. Covered Court": 5.69,
        "Pio Cruzcosa Empty Lot": 10.01,
        "Palimbang Empty Lot": 7.32,
        "Iba O'Este Empty Lot 1": 7.36,
        "Iba O'Este Empty Lot 2": 6.51,
        "Caniogan Empty Lot": 6.51,
        "Iba O'Este Empty Lot 3": 6.47,
        "Iba O'Este Empty Lot 4": 6.33,
        "Caniogan Empty Lot 2": 6.33,
        "Corazon Empty Lot 1": 6.11,
        "Corazon Empty Lot 2": 5.96,
        "Gugo Empty Lot": 5.96,
    },
    "distanceswork": {
         "Work1": 7.87
    }},
    {"name": "Danga Dike", "area1": 126, "cost1": 970200, "area2": 252, "cost2": 7560000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.28, 
        "F. Mendoza Memorial Elem Sch.": 4.38, 
        "Calumpit Sports Complex": 4.28,
        "Gatbuca Basketball Court": 3.72,
        "San Miguel Meysulao High School": 2.07,
        "Doña Damiana Elem School": 1.98,
        "Danga Dike": 0,
        "Meysulao Multipurpose/E.C.": 7.17,
        "Calizon Dike": 5.29,
        "San Marcos Elem. Sch.": 5.07,
        "San Marcos National H.S.": 7.16,
        "GMA Kapuso E.C.": 9.39,
        "NV9 Multi-Purpose": 7.06,
        "Frances E.C.": 4.05,
        "Balungao E.C.": 4.84,
        "Gugo E.C.": 6.96,
        "San Marcos E.C.": 7.14,
        "San Jose E.C.": 10.19,
        "MEYTO Multi-Purpose/ E.C.": 10.20,
        "Barangay Hall Bulusan": 7.40,
        "Brgy. Hall Sta. Lucia": 7.75,
        "Mun. Covered Court": 4.59,
        "Pio Cruzcosa Empty Lot": 8.90,
        "Palimbang Empty Lot": 6.22,
        "Iba O'Este Empty Lot 1": 6.25,
        "Iba O'Este Empty Lot 2": 5.39,
        "Caniogan Empty Lot": 5.39,
        "Iba O'Este Empty Lot 3": 5.36,
        "Iba O'Este Empty Lot 4": 5.22,
        "Caniogan Empty Lot 2": 5.22,
        "Corazon Empty Lot 1": 5.00,
        "Corazon Empty Lot 2": 4.86,
        "Gugo Empty Lot": 4.86,
    },
    "distanceswork": {
         "Work1": 6.77
    }},
    {"name": "Meysulao Multipurpose/E.C.", "area1": 100, "cost1": 770000, "area2": 200, "cost2": 6000000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.56, 
        "F. Mendoza Memorial Elem Sch.": 3.46, 
        "Calumpit Sports Complex": 3.56,
        "Gatbuca Basketball Court": 3.79,
        "San Miguel Meysulao High School": 8.37,
        "Doña Damiana Elem School": 8.28,
        "Danga Dike": 7.17,
        "Meysulao Multipurpose/E.C.": 0,
        "Calizon Dike": 1.95,
        "San Marcos Elem. Sch.": 5.49,
        "San Marcos National H.S.": 5.60,
        "GMA Kapuso E.C.": 7.83,
        "NV9 Multi-Purpose": 5.50,
        "Frances E.C.": 3.79,
        "Balungao E.C.": 2.55,
        "Gugo E.C.": 2.40,
        "San Marcos E.C.": 5.57,
        "San Jose E.C.": 3.34,
        "MEYTO Multi-Purpose/ E.C.": 3.34,
        "Barangay Hall Bulusan": 0.25,
        "Brgy. Hall Sta. Lucia": 1.02,
        "Mun. Covered Court": 2.95,
        "Pio Cruzcosa Empty Lot": 7.35,
        "Palimbang Empty Lot": 4.66,
        "Iba O'Este Empty Lot 1": 4.76,
        "Iba O'Este Empty Lot 2": 3.84,
        "Caniogan Empty Lot": 3.84,
        "Iba O'Este Empty Lot 3": 3.79,
        "Iba O'Este Empty Lot 4": 3.72,
        "Caniogan Empty Lot 2": 3.72,
        "Corazon Empty Lot 1": 3.50,
        "Corazon Empty Lot 2": 3.56,
        "Gugo Empty Lot": 3.56,
    },
    "distanceswork": {
         "Work1": 5.20
    }},
    {"name": "Calizon Dike", "area1": 126, "cost1": 970200, "area2": 252, "cost2": 7560000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.68, 
        "F. Mendoza Memorial Elem Sch.": 1.59, 
        "Calumpit Sports Complex": 1.68,
        "Gatbuca Basketball Court": 1.91,
        "San Miguel Meysulao High School": 6.49,
        "Doña Damiana Elem School": 6.40,
        "Danga Dike": 5.29,
        "Meysulao Multipurpose/E.C.": 1.95,
        "Calizon Dike": 0,
        "San Marcos Elem. Sch.": 3.67,
        "San Marcos National H.S.": 3.79,
        "GMA Kapuso E.C.": 6.01,
        "NV9 Multi-Purpose": 3.68,
        "Frances E.C.": 1.91,
        "Balungao E.C.": 0.67,
        "Gugo E.C.": 1.74,
        "San Marcos E.C.": 3.76,
        "San Jose E.C.": 4.97,
        "MEYTO Multi-Purpose/ E.C.": 4.98,
        "Barangay Hall Bulusan": 2.20,
        "Brgy. Hall Sta. Lucia": 2.53,
        "Mun. Covered Court": 1.07,
        "Pio Cruzcosa Empty Lot": 5.53,
        "Palimbang Empty Lot": 2.84,
        "Iba O'Este Empty Lot 1": 2.88,
        "Iba O'Este Empty Lot 2": 2.02,
        "Caniogan Empty Lot": 2.02,
        "Iba O'Este Empty Lot 3": 1.99,
        "Iba O'Este Empty Lot 4": 1.85,
        "Caniogan Empty Lot 2": 1.85,
        "Corazon Empty Lot 1": 1.63,
        "Corazon Empty Lot 2": 1.48,
        "Gugo Empty Lot": 1.48,
    },
    "distanceswork": {
         "Work1": 3.39
    }},
    {"name": "San Marcos Elem. Sch.", "area1": 1147, "cost1": 8831900, "area2": 2294, "cost2": 68820000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.28, 
        "F. Mendoza Memorial Elem Sch.": 3.09, 
        "Calumpit Sports Complex": 3.28,
        "Gatbuca Basketball Court": 3.67,
        "San Miguel Meysulao High School": 8.24,
        "Doña Damiana Elem School": 8.16,
        "Danga Dike": 7.05,
        "Meysulao Multipurpose/E.C.": 5.49,
        "Calizon Dike": 3.67,
        "San Marcos Elem. Sch.": 0,
        "San Marcos National H.S.": 0.52,
        "GMA Kapuso E.C.": 2.38,
        "NV9 Multi-Purpose": 2.17,
        "Frances E.C.": 3.67,
        "Balungao E.C.": 3.17,
        "Gugo E.C.": 3.69,
        "San Marcos E.C.": 0.12,
        "San Jose E.C.": 8.51,
        "MEYTO Multi-Purpose/ E.C.": 8.51,
        "Barangay Hall Bulusan": 5.74,
        "Brgy. Hall Sta. Lucia": 6.07,
        "Mun. Covered Court": 2.92,
        "Pio Cruzcosa Empty Lot": 2.10,
        "Palimbang Empty Lot": 0.83,
        "Iba O'Este Empty Lot 1": 2.09,
        "Iba O'Este Empty Lot 2": 1.66,
        "Caniogan Empty Lot": 1.66,
        "Iba O'Este Empty Lot 3": 1.69,
        "Iba O'Este Empty Lot 4": 1.83,
        "Caniogan Empty Lot 2": 1.83,
        "Corazon Empty Lot 1": 2.05,
        "Corazon Empty Lot 2": 2.19,
        "Gugo Empty Lot": 2.19,
    },
    "distanceswork": {
         "Work1": 0.68
    }},
        {"name": "San Marcos National H.S.", "area1": 6353, "cost1": 48918100, "area2": 12706, "cost2": 381180000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.39, 
        "F. Mendoza Memorial Elem Sch.": 3.21, 
        "Calumpit Sports Complex": 3.39,
        "Gatbuca Basketball Court": 3.39,
        "San Miguel Meysulao High School": 8.36,
        "Doña Damiana Elem School": 8.27,
        "Danga Dike": 7.16,
        "Meysulao Multipurpose/E.C.": 5.60,
        "Calizon Dike": 3.79,
        "San Marcos Elem. Sch.": 0.52,
        "San Marcos National H.S.": 0,
        "GMA Kapuso E.C.": 2.79,
        "NV9 Multi-Purpose": 2.29,
        "Frances E.C.": 3.78,
        "Balungao E.C.": 3.28,
        "Gugo E.C.": 3.80,
        "San Marcos E.C.": 0.65,
        "San Jose E.C.": 8.62,
        "MEYTO Multi-Purpose/ E.C.": 8.62,
        "Barangay Hall Bulusan": 5.85,
        "Brgy. Hall Sta. Lucia": 6.18,
        "Mun. Covered Court": 3.03,
        "Pio Cruzcosa Empty Lot": 1.89,
        "Palimbang Empty Lot": 0.94,
        "Iba O'Este Empty Lot 1": 2.21,
        "Iba O'Este Empty Lot 2": 1.77,
        "Caniogan Empty Lot": 1.77,
        "Iba O'Este Empty Lot 3": 1.80,
        "Iba O'Este Empty Lot 4": 1.95,
        "Caniogan Empty Lot 2": 1.95,
        "Corazon Empty Lot 1": 2.17,
        "Corazon Empty Lot 2": 2.31,
        "Gugo Empty Lot": 2.31,
    },
    "distanceswork": {
         "Work1": 0.39
    }},
    {"name": "GMA Kapuso E.C.", "area1": 200, "cost1": 1540000, "area2": 400, "cost2": 12000000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.62, 
        "F. Mendoza Memorial Elem Sch.": 5.43, 
        "Calumpit Sports Complex": 5.62,
        "Gatbuca Basketball Court": 6.01,
        "San Miguel Meysulao High School": 10.58,
        "Doña Damiana Elem School": 10.49,
        "Danga Dike": 9.39,
        "Meysulao Multipurpose/E.C.": 7.83,
        "Calizon Dike": 6.01,
        "San Marcos Elem. Sch.": 2.38,
        "San Marcos National H.S.": 2.79,
        "GMA Kapuso E.C.": 0,
        "NV9 Multi-Purpose": 4.51,
        "Frances E.C.": 6.01,
        "Balungao E.C.": 5.51,
        "Gugo E.C.": 6.03,
        "San Marcos E.C.": 2.25,
        "San Jose E.C.": 10.84,
        "MEYTO Multi-Purpose/ E.C.": 10.85,
        "Barangay Hall Bulusan": 8.08,
        "Brgy. Hall Sta. Lucia": 8.41,
        "Mun. Covered Court": 5.25,
        "Pio Cruzcosa Empty Lot": 2.26,
        "Palimbang Empty Lot": 4.53,
        "Iba O'Este Empty Lot 1": 5.79,
        "Iba O'Este Empty Lot 2": 5.35,
        "Caniogan Empty Lot": 5.35,
        "Iba O'Este Empty Lot 3": 5.39,
        "Iba O'Este Empty Lot 4": 5.53,
        "Caniogan Empty Lot 2": 5.53,
        "Corazon Empty Lot 1": 5.75,
        "Corazon Empty Lot 2": 5.89,
        "Gugo Empty Lot": 5.89,
    },
    "distanceswork": {
         "Work1": 3.03
    }},
    {"name": "NV9 Multi-Purpose", "area1": 2513, "cost1": 19350100, "area2": 5026, "cost2": 150780000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.29, 
        "F. Mendoza Memorial Elem Sch.": 3.12, 
        "Calumpit Sports Complex": 3.29,
        "Gatbuca Basketball Court": 3.68,
        "San Miguel Meysulao High School": 8.26,
        "Doña Damiana Elem School": 8.17,
        "Danga Dike": 7.06,
        "Meysulao Multipurpose/E.C.": 5.50,
        "Calizon Dike": 3.68,
        "San Marcos Elem. Sch.": 2.17,
        "San Marcos National H.S.": 2.29,
        "GMA Kapuso E.C.": 4.51,
        "NV9 Multi-Purpose": 0,
        "Frances E.C.": 3.68,
        "Balungao E.C.": 3.18,
        "Gugo E.C.": 3.70,
        "San Marcos E.C.": 2.26,
        "San Jose E.C.": 8.52,
        "MEYTO Multi-Purpose/ E.C.": 8.52,
        "Barangay Hall Bulusan": 5.75,
        "Brgy. Hall Sta. Lucia": 6.08,
        "Mun. Covered Court": 2.93,
        "Pio Cruzcosa Empty Lot": 4.03,
        "Palimbang Empty Lot": 1.34,
        "Iba O'Este Empty Lot 1": 2.21,
        "Iba O'Este Empty Lot 2": 1.66,
        "Caniogan Empty Lot": 1.66,
        "Iba O'Este Empty Lot 3": 1.70,
        "Iba O'Este Empty Lot 4": 1.84,
        "Caniogan Empty Lot 2": 1.84,
        "Corazon Empty Lot 1": 2.06,
        "Corazon Empty Lot 2": 2.20,
        "Gugo Empty Lot": 2.20,
    },
    "distanceswork": {
         "Work1": 1.89
    }},
    {"name": "Frances E.C.", "area1": 150, "cost1": 1155000, "area2": 300, "cost2": 9000000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.90, 
        "F. Mendoza Memorial Elem Sch.": 1.01, 
        "Calumpit Sports Complex": 0.90,
        "Gatbuca Basketball Court": 0.72,
        "San Miguel Meysulao High School": 5.25,
        "Doña Damiana Elem School": 5.16,
        "Danga Dike": 4.05,
        "Meysulao Multipurpose/E.C.": 3.79,
        "Calizon Dike": 1.91,
        "San Marcos Elem. Sch.": 3.67,
        "San Marcos National H.S.": 3.78,
        "GMA Kapuso E.C.": 6.01,
        "NV9 Multi-Purpose": 3.68,
        "Frances E.C.": 0,
        "Balungao E.C.": 1.46,
        "Gugo E.C.": 3.58,
        "San Marcos E.C.": 3.76,
        "San Jose E.C.": 6.81,
        "MEYTO Multi-Purpose/ E.C.": 6.82,
        "Barangay Hall Bulusan": 4.02,
        "Brgy. Hall Sta. Lucia": 4.37,
        "Mun. Covered Court": 1.21,
        "Pio Cruzcosa Empty Lot": 5.52,
        "Palimbang Empty Lot": 2.84,
        "Iba O'Este Empty Lot 1": 2.87,
        "Iba O'Este Empty Lot 2": 2.01,
        "Caniogan Empty Lot": 2.01,
        "Iba O'Este Empty Lot 3": 1.98,
        "Iba O'Este Empty Lot 4": 1.84,
        "Caniogan Empty Lot 2": 1.84,
        "Corazon Empty Lot 1": 1.62,
        "Corazon Empty Lot 2": 1.47,
        "Gugo Empty Lot": 1.47,
    },
    "distanceswork": {
         "Work1": 3.39
    }},
    {"name": "Balungao E.C.", "area1": 216, "cost1": 1663200, "area2": 432, "cost2": 12960000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.07, 
        "F. Mendoza Memorial Elem Sch.": 0.91, 
        "Calumpit Sports Complex": 1.07,
        "Gatbuca Basketball Court": 1.46,
        "San Miguel Meysulao High School": 6.04,
        "Doña Damiana Elem School": 5.95,
        "Danga Dike": 4.84,
        "Meysulao Multipurpose/E.C.": 2.55,
        "Calizon Dike": 0.67,
        "San Marcos Elem. Sch.": 3.17,
        "San Marcos National H.S.": 3.28,
        "GMA Kapuso E.C.": 5.51,
        "NV9 Multi-Purpose": 3.18,
        "Frances E.C.": 1.46,
        "Balungao E.C.": 0,
        "Gugo E.C.": 2.34,
        "San Marcos E.C.": 3.26,
        "San Jose E.C.": 5.57,
        "MEYTO Multi-Purpose/ E.C.": 5.58,
        "Barangay Hall Bulusan": 2.80,
        "Brgy. Hall Sta. Lucia": 3.13,
        "Mun. Covered Court": 0.39,
        "Pio Cruzcosa Empty Lot": 5.03,
        "Palimbang Empty Lot": 2.34,
        "Iba O'Este Empty Lot 1": 2.37,
        "Iba O'Este Empty Lot 2": 1.52,
        "Caniogan Empty Lot": 1.52,
        "Iba O'Este Empty Lot 3": 1.48,
        "Iba O'Este Empty Lot 4": 1.34,
        "Caniogan Empty Lot 2": 1.34,
        "Corazon Empty Lot 1": 1.12,
        "Corazon Empty Lot 2": 0.97,
        "Gugo Empty Lot": 0.97,
    },
    "distanceswork": {
         "Work1": 2.89
    }},
    {"name": "Gugo E.C.", "area1": 336, "cost1": 2587200, "area2": 672, "cost2": 20160000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.34, 
        "F. Mendoza Memorial Elem Sch.": 3.25, 
        "Calumpit Sports Complex": 3.34,
        "Gatbuca Basketball Court": 3.58,
        "San Miguel Meysulao High School": 8.15,
        "Doña Damiana Elem School": 8.06,
        "Danga Dike": 6.96,
        "Meysulao Multipurpose/E.C.": 2.40,
        "Calizon Dike": 1.74,
        "San Marcos Elem. Sch.": 3.69,
        "San Marcos National H.S.": 3.80,
        "GMA Kapuso E.C.": 6.03,
        "NV9 Multi-Purpose": 3.70,
        "Frances E.C.": 3.58,
        "Balungao E.C.": 2.34,
        "Gugo E.C.": 0,
        "San Marcos E.C.": 3.78,
        "San Jose E.C.": 5.40,
        "MEYTO Multi-Purpose/ E.C.": 5.41,
        "Barangay Hall Bulusan": 2.65,
        "Brgy. Hall Sta. Lucia": 2.97,
        "Mun. Covered Court": 2.73,
        "Pio Cruzcosa Empty Lot": 5.54,
        "Palimbang Empty Lot": 2.85,
        "Iba O'Este Empty Lot 1": 3.21,
        "Iba O'Este Empty Lot 2": 2.03,
        "Caniogan Empty Lot": 2.03,
        "Iba O'Este Empty Lot 3": 2.00,
        "Iba O'Este Empty Lot 4": 2.03,
        "Caniogan Empty Lot 2": 2.03,
        "Corazon Empty Lot 1": 2.25,
        "Corazon Empty Lot 2": 2.39,
        "Gugo Empty Lot": 2.39,
    },
    "distanceswork": {
         "Work1": 3.41
    }},
        {"name": "San Marcos E.C.", "area1": 40, "cost1": 308000, "area2": 80, "cost2": 2400000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.37, 
        "F. Mendoza Memorial Elem Sch.": 3.18, 
        "Calumpit Sports Complex": 3.37,
        "Gatbuca Basketball Court": 3.76,
        "San Miguel Meysulao High School": 8.33,
        "Doña Damiana Elem School": 8.24,
        "Danga Dike": 7.14,
        "Meysulao Multipurpose/E.C.": 5.57,
        "Calizon Dike": 3.76,
        "San Marcos Elem. Sch.": 0.12,
        "San Marcos National H.S.": 0.65,
        "GMA Kapuso E.C.": 2.25,
        "NV9 Multi-Purpose": 2.26,
        "Frances E.C.": 3.76,
        "Balungao E.C.": 3.26,
        "Gugo E.C.": 3.78,
        "San Marcos E.C.": 0,
        "San Jose E.C.": 8.59,
        "MEYTO Multi-Purpose/ E.C.": 8.83,
        "Barangay Hall Bulusan": 5.83,
        "Brgy. Hall Sta. Lucia": 6.16,
        "Mun. Covered Court": 3.00,
        "Pio Cruzcosa Empty Lot": 2.10,
        "Palimbang Empty Lot": 0.94,
        "Iba O'Este Empty Lot 1": 2.18,
        "Iba O'Este Empty Lot 2": 1.74,
        "Caniogan Empty Lot": 1.74,
        "Iba O'Este Empty Lot 3": 1.78,
        "Iba O'Este Empty Lot 4": 1.91,
        "Caniogan Empty Lot 2": 1.91,
        "Corazon Empty Lot 1": 2.14,
        "Corazon Empty Lot 2": 2.28,
        "Gugo Empty Lot": 2.28,
    },
    "distanceswork": {
         "Work1": 0.81
    }},
    {"name": "San Jose E.C.", "area1": 268, "cost1": 2063600, "area2": 536, "cost2": 16080000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 6.58, 
        "F. Mendoza Memorial Elem Sch.": 6.48, 
        "Calumpit Sports Complex": 6.58,
        "Gatbuca Basketball Court": 6.81,
        "San Miguel Meysulao High School": 11.38,
        "Doña Damiana Elem School": 11.30,
        "Danga Dike": 10.19,
        "Meysulao Multipurpose/E.C.": 3.34,
        "Calizon Dike": 4.97,
        "San Marcos Elem. Sch.": 8.51,
        "San Marcos National H.S.": 8.62,
        "GMA Kapuso E.C.": 10.84,
        "NV9 Multi-Purpose": 8.52,
        "Frances E.C.": 6.81,
        "Balungao E.C.": 5.57,
        "Gugo E.C.": 5.40,
        "San Marcos E.C.": 8.59,
        "San Jose E.C.": 0,
        "MEYTO Multi-Purpose/ E.C.": 0.76,
        "Barangay Hall Bulusan": 3.59,
        "Brgy. Hall Sta. Lucia": 2.43,
        "Mun. Covered Court": 5.96,
        "Pio Cruzcosa Empty Lot": 10.36,
        "Palimbang Empty Lot": 7.67,
        "Iba O'Este Empty Lot 1": 7.77,
        "Iba O'Este Empty Lot 2": 6.85,
        "Caniogan Empty Lot": 6.85,
        "Iba O'Este Empty Lot 3": 6.81,
        "Iba O'Este Empty Lot 4": 6.74,
        "Caniogan Empty Lot 2": 6.74,
        "Corazon Empty Lot 1": 6.52,
        "Corazon Empty Lot 2": 6.37,
        "Gugo Empty Lot": 6.37,
    },
    "distanceswork": {
         "Work1": 8.22
    }},
        {"name": "MEYTO Multi-Purpose/ E.C.", "area1": 142, "cost1": 1093400, "area2": 284, "cost2": 8520000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 6.58, 
        "F. Mendoza Memorial Elem Sch.": 6.49, 
        "Calumpit Sports Complex": 6.58,
        "Gatbuca Basketball Court": 6.82,
        "San Miguel Meysulao High School": 11.39,
        "Doña Damiana Elem School": 11.30,
        "Danga Dike": 10.20,
        "Meysulao Multipurpose/E.C.": 3.34,
        "Calizon Dike": 4.98,
        "San Marcos Elem. Sch.": 8.51,
        "San Marcos National H.S.": 8.62,
        "GMA Kapuso E.C.": 10.85,
        "NV9 Multi-Purpose": 8.52,
        "Frances E.C.": 6.82,
        "Balungao E.C.": 5.58,
        "Gugo E.C.": 5.41,
        "San Marcos E.C.": 8.60,
        "San Jose E.C.": 0.76,
        "MEYTO Multi-Purpose/ E.C.": 0,
        "Barangay Hall Bulusan": 3.59,
        "Brgy. Hall Sta. Lucia": 2.44,
        "Mun. Covered Court": 5.97,
        "Pio Cruzcosa Empty Lot": 10.37,
        "Palimbang Empty Lot": 7.68,
        "Iba O'Este Empty Lot 1": 7.78,
        "Iba O'Este Empty Lot 2": 6.86,
        "Caniogan Empty Lot": 6.86,
        "Iba O'Este Empty Lot 3": 6.82,
        "Iba O'Este Empty Lot 4": 6.74,
        "Caniogan Empty Lot 2": 6.74,
        "Corazon Empty Lot 1": 6.52,
        "Corazon Empty Lot 2": 6.38,
        "Gugo Empty Lot": 6.38,
    },
    "distanceswork": {
         "Work1": 8.23
    }},
    {"name": "Barangay Hall Bulusan", "area1": 700, "cost1": 5390000, "area2": 1400, "cost2": 42000000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 3.79, 
        "F. Mendoza Memorial Elem Sch.": 3.72, 
        "Calumpit Sports Complex": 3.79,
        "Gatbuca Basketball Court": 4.02,
        "San Miguel Meysulao High School": 8.60,
        "Doña Damiana Elem School": 8.51,
        "Danga Dike": 7.40,
        "Meysulao Multipurpose/E.C.": 0.25,
        "Calizon Dike": 2.20,
        "San Marcos Elem. Sch.": 5.74,
        "San Marcos National H.S.": 5.85,
        "GMA Kapuso E.C.": 8.08,
        "NV9 Multi-Purpose": 5.75,
        "Frances E.C.": 4.02,
        "Balungao E.C.": 2.80,
        "Gugo E.C.": 2.65,
        "San Marcos E.C.": 5.83,
        "San Jose E.C.": 3.59,
        "MEYTO Multi-Purpose/ E.C.": 3.59,
        "Barangay Hall Bulusan": 0,
        "Brgy. Hall Sta. Lucia": 1.27,
        "Mun. Covered Court": 3.20,
        "Pio Cruzcosa Empty Lot": 7.59,
        "Palimbang Empty Lot": 4.90,
        "Iba O'Este Empty Lot 1": 5.00,
        "Iba O'Este Empty Lot 2": 4.08,
        "Caniogan Empty Lot": 4.08,
        "Iba O'Este Empty Lot 3": 4.04,
        "Iba O'Este Empty Lot 4": 3.97,
        "Caniogan Empty Lot 2": 3.97,
        "Corazon Empty Lot 1": 3.75,
        "Corazon Empty Lot 2": 3.61,
        "Gugo Empty Lot": 3.61,
    },
    "distanceswork": {
         "Work1": 5.46
    }},
        {"name": "Brgy. Hall Sta. Lucia", "area1": 150, "cost1": 1155000, "area2": 300, "cost2": 9000000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 4.14, 
        "F. Mendoza Memorial Elem Sch.": 4.05, 
        "Calumpit Sports Complex": 4.14,
        "Gatbuca Basketball Court": 4.37,
        "San Miguel Meysulao High School": 8.95,
        "Doña Damiana Elem School": 8.86,
        "Danga Dike": 7.75,
        "Meysulao Multipurpose/E.C.": 1.02,
        "Calizon Dike": 2.53,
        "San Marcos Elem. Sch.": 6.07,
        "San Marcos National H.S.": 6.18,
        "GMA Kapuso E.C.": 8.41,
        "NV9 Multi-Purpose": 6.08,
        "Frances E.C.": 4.37,
        "Balungao E.C.": 3.13,
        "Gugo E.C.": 2.97,
        "San Marcos E.C.": 6.16,
        "San Jose E.C.": 2.43,
        "MEYTO Multi-Purpose/ E.C.": 2.44,
        "Barangay Hall Bulusan": 1.27,
        "Brgy. Hall Sta. Lucia": 0,
        "Mun. Covered Court": 3.53,
        "Pio Cruzcosa Empty Lot": 7.92,
        "Palimbang Empty Lot": 5.23,
        "Iba O'Este Empty Lot 1": 5.33,
        "Iba O'Este Empty Lot 2": 4.41,
        "Caniogan Empty Lot": 4.41,
        "Iba O'Este Empty Lot 3": 4.38,
        "Iba O'Este Empty Lot 4": 4.30,
        "Caniogan Empty Lot 2": 4.30,
        "Corazon Empty Lot 1": 4.08,
        "Corazon Empty Lot 2": 3.94,
        "Gugo Empty Lot": 3.94,
    },
    "distanceswork": {
         "Work1": 5.79
    }},
    {"name": "Mun. Covered Court", "area1": 713, "cost1": 5490100, "area2": 1426, "cost2": 42780000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 0.82, 
        "F. Mendoza Memorial Elem Sch.": 0.65, 
        "Calumpit Sports Complex": 0.82,
        "Gatbuca Basketball Court": 1.21,
        "San Miguel Meysulao High School": 5.78,
        "Doña Damiana Elem School": 5.69,
        "Danga Dike": 4.59,
        "Meysulao Multipurpose/E.C.": 2.95,
        "Calizon Dike": 1.07,
        "San Marcos Elem. Sch.": 2.92,
        "San Marcos National H.S.": 3.03,
        "GMA Kapuso E.C.": 5.25,
        "NV9 Multi-Purpose": 2.93,
        "Frances E.C.": 1.21,
        "Balungao E.C.": 0.39,
        "Gugo E.C.": 2.73,
        "San Marcos E.C.": 3.00,
        "San Jose E.C.": 5.96,
        "MEYTO Multi-Purpose/ E.C.": 5.97,
        "Barangay Hall Bulusan": 3.20,
        "Brgy. Hall Sta. Lucia": 3.53,
        "Mun. Covered Court": 0,
        "Pio Cruzcosa Empty Lot": 4.77,
        "Palimbang Empty Lot": 2.08,
        "Iba O'Este Empty Lot 1": 2.11,
        "Iba O'Este Empty Lot 2": 1.26,
        "Caniogan Empty Lot": 1.26,
        "Iba O'Este Empty Lot 3": 1.22,
        "Iba O'Este Empty Lot 4": 1.08,
        "Caniogan Empty Lot 2": 1.08,
        "Corazon Empty Lot 1": 0.86,
        "Corazon Empty Lot 2": 0.72,
        "Gugo Empty Lot": 0.72,
    },
    "distanceswork": {
         "Work1": 2.63
    }},
    # started here update distances
    {"name": "Pio Cruzcosa Empty Lot", "area1": 3870, "cost1": 280575000, "area2": 7740, "cost2": 512775000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 5.13, 
        "F. Mendoza Memorial Elem Sch.": 4.95, 
        "Calumpit Sports Complex": 5.13,
        "Gatbuca Basketball Court": 5.52,
        "San Miguel Meysulao High School": 10.10,
        "Doña Damiana Elem School": 10.01,
        "Danga Dike": 8.90,
        "Meysulao Multipurpose/E.C.": 7.34,
        "Calizon Dike": 5.52,
        "San Marcos Elem. Sch.": 2.10,
        "San Marcos National H.S.": 1.89,
        "GMA Kapuso E.C.": 2.24,
        "NV9 Multi-Purpose": 4.03,
        "Frances E.C.": 5.52,
        "Balungao E.C.": 5.03,
        "Gugo E.C.": 5.54,
        "San Marcos E.C.": 2.10,
        "San Jose E.C.": 10.36,
        "MEYTO Multi-Purpose/ E.C.": 10.37,
        "Barangay Hall Bulusan": 7.59,
        "Brgy. Hall Sta. Lucia": 7.92,
        "Mun. Covered Court": 4.77, 
        "Pio Cruzcosa Empty Lot": 0,
        "Palimbang Empty Lot": 2.69,
        "Iba O'Este Empty Lot 1": 3.95,
        "Iba O'Este Empty Lot 2": 3.50,
        "Caniogan Empty Lot": 3.50,
        "Iba O'Este Empty Lot 3": 3.54,
        "Iba O'Este Empty Lot 4": 3.68,
        "Caniogan Empty Lot 2": 3.68,
        "Corazon Empty Lot 1": 3.90,
        "Corazon Empty Lot 2": 4.05,
        "Gugo Empty Lot": 4.05,
    },
    "distanceswork": {
         "Work1": 2.13
    }},
    {"name": "Palimbang Empty Lot", "area1": 1903, "cost1": 137967500, "area2": 3806, "cost2": 252147500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.44, 
        "F. Mendoza Memorial Elem Sch.": 2.26, 
        "Calumpit Sports Complex": 2.44,
        "Gatbuca Basketball Court": 2.83,
        "San Miguel Meysulao High School": 7.41,
        "Doña Damiana Elem School": 7.32,
        "Danga Dike": 6.21,
        "Meysulao Multipurpose/E.C.": 4.65,
        "Calizon Dike": 2.84,
        "San Marcos Elem. Sch.": 0.83,
        "San Marcos National H.S.": 0.94,
        "GMA Kapuso E.C.": 4.51,
        "NV9 Multi-Purpose": 1.34,
        "Frances E.C.": 2.83,
        "Balungao E.C.": 2.34,
        "Gugo E.C.": 2.85,
        "San Marcos E.C.": 0.94,
        "San Jose E.C.": 7.67,
        "MEYTO Multi-Purpose/ E.C.": 7.68,
        "Barangay Hall Bulusan": 4.90,
        "Brgy. Hall Sta. Lucia": 5.23,
        "Mun. Covered Court": 2.08, 
        "Pio Cruzcosa Empty Lot": 2.69,
        "Palimbang Empty Lot": 0,
        "Iba O'Este Empty Lot 1": 1.26,
        "Iba O'Este Empty Lot 2": 0.81,
        "Caniogan Empty Lot": 0.81,
        "Iba O'Este Empty Lot 3": 0.85,
        "Iba O'Este Empty Lot 4": 0.99,
        "Caniogan Empty Lot 2": 0.99,
        "Corazon Empty Lot 1": 1.21,
        "Corazon Empty Lot 2": 1.36,
        "Gugo Empty Lot": 1.36,
    },
    "distanceswork": {
         "Work1": 0.56
    }},
    {"name": "Iba O'Este Empty Lot 1", "area1": 227, "cost1": 16457500, "area2": 454, "cost2": 30077500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 2.30, 
        "F. Mendoza Memorial Elem Sch.": 2.01, 
        "Calumpit Sports Complex": 2.30,
        "Gatbuca Basketball Court": 2.87,
        "San Miguel Meysulao High School": 7.44,
        "Doña Damiana Elem School": 7.35,
        "Danga Dike": 6.25,
        "Meysulao Multipurpose/E.C.": 4.75,
        "Calizon Dike": 2.87,
        "San Marcos Elem. Sch.": 2.09,
        "San Marcos National H.S.": 2.21,
        "GMA Kapuso E.C.": 5.78,
        "NV9 Multi-Purpose": 2.21,
        "Frances E.C.": 2.87,
        "Balungao E.C.": 2.37,
        "Gugo E.C.": 3.21,
        "San Marcos E.C.": 2.18,
        "San Jose E.C.": 7.77,
        "MEYTO Multi-Purpose/ E.C.": 7.87,
        "Barangay Hall Bulusan": 5.00,
        "Brgy. Hall Sta. Lucia": 5.33,
        "Mun. Covered Court": 2.11, 
        "Pio Cruzcosa Empty Lot": 3.95,
        "Palimbang Empty Lot": 1.26,
        "Iba O'Este Empty Lot 1": 0,
        "Iba O'Este Empty Lot 2": 1.35,
        "Caniogan Empty Lot": 1.35,
        "Iba O'Este Empty Lot 3": 1.31,
        "Iba O'Este Empty Lot 4": 1.17,
        "Caniogan Empty Lot 2": 1.17,
        "Corazon Empty Lot 1": 1.25,
        "Corazon Empty Lot 2": 1.39,
        "Gugo Empty Lot": 1.39,
    },
    "distanceswork": {
         "Work1": 1.37
    }},
    {"name": "Iba O'Este Empty Lot 2", "area1": 308, "cost1": 22330000, "area2": 616, "cost2": 40810000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.62, 
        "F. Mendoza Memorial Elem Sch.": 1.46, 
        "Calumpit Sports Complex": 1.62,
        "Gatbuca Basketball Court": 2.01,
        "San Miguel Meysulao High School": 6.59,
        "Doña Damiana Elem School": 6.50,
        "Danga Dike": 5.39,
        "Meysulao Multipurpose/E.C.": 3.83,
        "Calizon Dike": 2.02,
        "San Marcos Elem. Sch.": 1.65,
        "San Marcos National H.S.": 1.76,
        "GMA Kapuso E.C.": 5.33,
        "NV9 Multi-Purpose": 1.66,
        "Frances E.C.": 2.01,
        "Balungao E.C.": 1.52,
        "Gugo E.C.": 2.03,
        "San Marcos E.C.": 1.74,
        "San Jose E.C.": 6.85,
        "MEYTO Multi-Purpose/ E.C.": 6.86,
        "Barangay Hall Bulusan": 4.08,
        "Brgy. Hall Sta. Lucia": 4.41,
        "Mun. Covered Court": 1.26, 
        "Pio Cruzcosa Empty Lot": 3.50,
        "Palimbang Empty Lot": 0.81,
        "Iba O'Este Empty Lot 1": 1.35,
        "Iba O'Este Empty Lot 2": 0,
        "Caniogan Empty Lot": 0,
        "Iba O'Este Empty Lot 3": 0.03,
        "Iba O'Este Empty Lot 4": 0.17,
        "Caniogan Empty Lot 2": 0.17,
        "Corazon Empty Lot 1": 0.39,
        "Corazon Empty Lot 2": 0.54,
        "Gugo Empty Lot": 0.54,
    },
    "distanceswork": {
         "Work1": 1.37
    }},
    {"name": "Caniogan Empty Lot", "area1": 328, "cost1": 23780000, "area2": 656, "cost2": 43460000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.62, 
        "F. Mendoza Memorial Elem Sch.": 1.46, 
        "Calumpit Sports Complex": 1.62,
        "Gatbuca Basketball Court": 2.01,
        "San Miguel Meysulao High School": 6.59,
        "Doña Damiana Elem School": 6.50,
        "Danga Dike": 5.39,
        "Meysulao Multipurpose/E.C.": 3.83,
        "Calizon Dike": 2.02,
        "San Marcos Elem. Sch.": 1.65,
        "San Marcos National H.S.": 1.76,
        "GMA Kapuso E.C.": 5.33,
        "NV9 Multi-Purpose": 1.66,
        "Frances E.C.": 2.01,
        "Balungao E.C.": 1.52,
        "Gugo E.C.": 2.03,
        "San Marcos E.C.": 1.74,
        "San Jose E.C.": 6.85,
        "MEYTO Multi-Purpose/ E.C.": 6.86,
        "Barangay Hall Bulusan": 4.08,
        "Brgy. Hall Sta. Lucia": 4.41,
        "Mun. Covered Court": 1.26, 
        "Pio Cruzcosa Empty Lot": 3.50,
        "Palimbang Empty Lot": 0.81,
        "Iba O'Este Empty Lot 1": 1.35,
        "Iba O'Este Empty Lot 2": 0,
        "Caniogan Empty Lot": 0,
        "Iba O'Este Empty Lot 3": 0.03,
        "Iba O'Este Empty Lot 4": 0.17,
        "Caniogan Empty Lot 2": 0.17,
        "Corazon Empty Lot 1": 0.39,
        "Corazon Empty Lot 2": 0.54,
        "Gugo Empty Lot": 0.54,   
        },
    "distanceswork": {
         "Work1": 1.37
    }},
    {"name": "Pio Cruzcosa Empty Lot", "area1": 361, "cost1": 26172500, "area2": 722, "cost2": 47832500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.59, 
        "F. Mendoza Memorial Elem Sch.": 1.42, 
        "Calumpit Sports Complex": 1.59,
        "Gatbuca Basketball Court": 1.98,
        "San Miguel Meysulao High School": 6.55,
        "Doña Damiana Elem School": 6.46,
        "Danga Dike": 5.36,
        "Meysulao Multipurpose/E.C.": 3.79,
        "Calizon Dike": 1.98,
        "San Marcos Elem. Sch.": 1.69,
        "San Marcos National H.S.": 1.80,
        "GMA Kapuso E.C.": 5.37,
        "NV9 Multi-Purpose": 1.70,
        "Frances E.C.": 1.98,
        "Balungao E.C.": 1.48,
        "Gugo E.C.": 2.00,
        "San Marcos E.C.": 1.78,
        "San Jose E.C.": 6.81,
        "MEYTO Multi-Purpose/ E.C.": 6.82,
        "Barangay Hall Bulusan": 4.04,
        "Brgy. Hall Sta. Lucia": 4.38,
        "Mun. Covered Court": 1.22, 
        "Pio Cruzcosa Empty Lot": 3.54,
        "Palimbang Empty Lot": 0.85,
        "Iba O'Este Empty Lot 1": 1.31,
        "Iba O'Este Empty Lot 2": 0.03,
        "Caniogan Empty Lot": 0.03,
        "Iba O'Este Empty Lot 3": 0,
        "Iba O'Este Empty Lot 4": 0.13,
        "Caniogan Empty Lot 2": 0.13,
        "Corazon Empty Lot 1": 0.35,
        "Corazon Empty Lot 2": 0.50,
        "Gugo Empty Lot": 0.50,
    },
    "distanceswork": {
         "Work1": 1.41
    }},
    {"name": "Iba O'Este Empty Lot 4", "area1": 287, "cost1": 20807500, "area2": 574, "cost2": 38027500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.45, 
        "F. Mendoza Memorial Elem Sch.": 1.28, 
        "Calumpit Sports Complex": 1.45,
        "Gatbuca Basketball Court": 1.84,
        "San Miguel Meysulao High School": 6.41,
        "Doña Damiana Elem School": 6.32,
        "Danga Dike": 5.22,
        "Meysulao Multipurpose/E.C.": 3.72,
        "Calizon Dike": 1.84,
        "San Marcos Elem. Sch.": 1.83,
        "San Marcos National H.S.": 1.94,
        "GMA Kapuso E.C.": 5.51,
        "NV9 Multi-Purpose": 1.84,
        "Frances E.C.": 1.84,
        "Balungao E.C.": 1.34,
        "Gugo E.C.": 2.03,
        "San Marcos E.C.": 1.91,
        "San Jose E.C.": 6.74,
        "MEYTO Multi-Purpose/ E.C.": 6.74,
        "Barangay Hall Bulusan": 3.97,
        "Brgy. Hall Sta. Lucia": 4.30,
        "Mun. Covered Court": 1.08, 
        "Pio Cruzcosa Empty Lot": 3.68,
        "Palimbang Empty Lot": 0.99,
        "Iba O'Este Empty Lot 1": 1.17,
        "Iba O'Este Empty Lot 2": 0.17,
        "Caniogan Empty Lot": 0.17,
        "Iba O'Este Empty Lot 3": 0.13,
        "Iba O'Este Empty Lot 4": 0,
        "Caniogan Empty Lot 2": 0,
        "Corazon Empty Lot 1": 0.22,
        "Corazon Empty Lot 2": 0.36,
        "Gugo Empty Lot": 0.36,
    },
    "distanceswork": {
         "Work1": 1.55
    }},
    {"name": "Caniogan Empty Lot 2", "area1": 605, "cost1": 43862500, "area2": 1210, "cost2": 80162500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.45, 
        "F. Mendoza Memorial Elem Sch.": 1.28, 
        "Calumpit Sports Complex": 1.45,
        "Gatbuca Basketball Court": 1.84,
        "San Miguel Meysulao High School": 6.41,
        "Doña Damiana Elem School": 6.32,
        "Danga Dike": 5.22,
        "Meysulao Multipurpose/E.C.": 3.72,
        "Calizon Dike": 1.84,
        "San Marcos Elem. Sch.": 1.83,
        "San Marcos National H.S.": 1.94,
        "GMA Kapuso E.C.": 5.51,
        "NV9 Multi-Purpose": 1.84,
        "Frances E.C.": 1.84,
        "Balungao E.C.": 1.34,
        "Gugo E.C.": 2.03,
        "San Marcos E.C.": 1.91,
        "San Jose E.C.": 6.74,
        "MEYTO Multi-Purpose/ E.C.": 6.74,
        "Barangay Hall Bulusan": 3.97,
        "Brgy. Hall Sta. Lucia": 4.30,
        "Mun. Covered Court": 1.08, 
        "Pio Cruzcosa Empty Lot": 3.68,
        "Palimbang Empty Lot": 0.99,
        "Iba O'Este Empty Lot 1": 1.17,
        "Iba O'Este Empty Lot 2": 0.17,
        "Caniogan Empty Lot": 0.17,
        "Iba O'Este Empty Lot 3": 0.13,
        "Iba O'Este Empty Lot 4": 0,
        "Caniogan Empty Lot 2": 0,
        "Corazon Empty Lot 1": 0.22,
        "Corazon Empty Lot 2": 0.36,
        "Gugo Empty Lot": 0.36,
    },
    "distanceswork": {
         "Work1": 1.55
    }},
    {"name": "Corazon Empty Lot 1", "area1": 1022, "cost1": 74095000, "area2": 2044, "cost2": 135415000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.23, 
        "F. Mendoza Memorial Elem Sch.": 1.06, 
        "Calumpit Sports Complex": 1.23,
        "Gatbuca Basketball Court": 1.62,
        "San Miguel Meysulao High School": 6.19,
        "Doña Damiana Elem School": 6.10,
        "Danga Dike": 5.00,
        "Meysulao Multipurpose/E.C.": 3.50,
        "Calizon Dike": 1.62,
        "San Marcos Elem. Sch.": 2.05,
        "San Marcos National H.S.": 2.16,
        "GMA Kapuso E.C.": 5.73,
        "NV9 Multi-Purpose": 2.06,
        "Frances E.C.": 1.62,
        "Balungao E.C.": 1.12,
        "Gugo E.C.": 2.25,
        "San Marcos E.C.": 2.14,
        "San Jose E.C.": 6.52,
        "MEYTO Multi-Purpose/ E.C.": 6.52,
        "Barangay Hall Bulusan": 3.75,
        "Brgy. Hall Sta. Lucia": 4.08,
        "Mun. Covered Court": 0.86, 
        "Pio Cruzcosa Empty Lot": 3.90,
        "Palimbang Empty Lot": 1.21,
        "Iba O'Este Empty Lot 1": 1.25,
        "Iba O'Este Empty Lot 2": 0.39,
        "Caniogan Empty Lot": 0.39,
        "Iba O'Este Empty Lot 3": 0.35,
        "Iba O'Este Empty Lot 4": 0.22,
        "Caniogan Empty Lot 2": 0.22,
        "Corazon Empty Lot 1": 0,
        "Corazon Empty Lot 2": 0.14,
        "Gugo Empty Lot": 0.14,
    },
    "distanceswork": {
         "Work1": 1.78
    }},
    {"name": "Corazon Empty Lot 2", "area1": 394, "cost1": 28565000, "area2": 788, "cost2": 52205000, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.08, 
        "F. Mendoza Memorial Elem Sch.": 0.92, 
        "Calumpit Sports Complex": 1.08,
        "Gatbuca Basketball Court": 1.47,
        "San Miguel Meysulao High School": 6.05,
        "Doña Damiana Elem School": 5.96,
        "Danga Dike": 4.85,
        "Meysulao Multipurpose/E.C.": 3.35,
        "Calizon Dike": 1.48,
        "San Marcos Elem. Sch.": 2.19,
        "San Marcos National H.S.": 2.31,
        "GMA Kapuso E.C.": 5.88,
        "NV9 Multi-Purpose": 2.20,
        "Frances E.C.": 1.47,
        "Balungao E.C.": 0.97,
        "Gugo E.C.": 2.39,
        "San Marcos E.C.": 2.38,
        "San Jose E.C.": 6.37,
        "MEYTO Multi-Purpose/ E.C.": 6.38,
        "Barangay Hall Bulusan": 3.61,
        "Brgy. Hall Sta. Lucia": 3.91,
        "Mun. Covered Court": 0.72, 
        "Pio Cruzcosa Empty Lot": 4.05,
        "Palimbang Empty Lot": 1.36,
        "Iba O'Este Empty Lot 1": 1.39,
        "Iba O'Este Empty Lot 2": 0.54,
        "Caniogan Empty Lot": 0.54,
        "Iba O'Este Empty Lot 3": 0.50,
        "Iba O'Este Empty Lot 4": 0.36,
        "Caniogan Empty Lot 2": 0.36,
        "Corazon Empty Lot 1": 0.14,
        "Corazon Empty Lot 2": 0,
        "Gugo Empty Lot": 0,
    },
    "distanceswork": {
         "Work1": 1.93
    }},
    {"name": "Gugo Empty Lot", "area1": 527, "cost1": 38207500, "area2": 1054, "cost2": 69827500, 
     "distances": {
        "BMLTC Multi-Purpose Bldg and EC": 1.08, 
        "F. Mendoza Memorial Elem Sch.": 0.92, 
        "Calumpit Sports Complex": 1.08,
        "Gatbuca Basketball Court": 1.47,
        "San Miguel Meysulao High School": 6.05,
        "Doña Damiana Elem School": 5.96,
        "Danga Dike": 4.85,
        "Meysulao Multipurpose/E.C.": 3.35,
        "Calizon Dike": 1.48,
        "San Marcos Elem. Sch.": 2.19,
        "San Marcos National H.S.": 2.31,
        "GMA Kapuso E.C.": 5.88,
        "NV9 Multi-Purpose": 2.20,
        "Frances E.C.": 1.47,
        "Balungao E.C.": 0.97,
        "Gugo E.C.": 2.39,
        "San Marcos E.C.": 2.28,
        "San Jose E.C.": 6.37,
        "MEYTO Multi-Purpose/ E.C.": 6.38,
        "Barangay Hall Bulusan": 3.61,
        "Brgy. Hall Sta. Lucia": 3.94,
        "Mun. Covered Court": 0.72, 
        "Pio Cruzcosa Empty Lot": 4.05,
        "Palimbang Empty Lot": 1.36,
        "Iba O'Este Empty Lot 1": 1.39,
        "Iba O'Este Empty Lot 2": 0.54,
        "Caniogan Empty Lot": 0.54,
        "Iba O'Este Empty Lot 3": 0.50,
        "Iba O'Este Empty Lot 4": 0.36,
        "Caniogan Empty Lot 2": 0.36,
        "Corazon Empty Lot 1": 0.14,
        "Corazon Empty Lot 2": 0,
        "Gugo Empty Lot": 0,
    },
    "distanceswork": {
         "Work1": 1.91
    }},
]