# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(624, 353)
        self.label = QtWidgets.QLabel(parent=widget)
        self.label.setGeometry(QtCore.QRect(100, 10, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.kilo_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.kilo_lineEdit.setGeometry(QtCore.QRect(20, 100, 271, 41))
        self.kilo_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.kilo_lineEdit.setObjectName("kilo_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=widget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=widget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pound_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.pound_lineEdit.setGeometry(QtCore.QRect(20, 190, 271, 41))
        self.pound_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.pound_lineEdit.setObjectName("pound_lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=widget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ounce_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.ounce_lineEdit.setGeometry(QtCore.QRect(20, 280, 271, 41))
        self.ounce_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.ounce_lineEdit.setObjectName("ounce_lineEdit")
        self.meter_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.meter_lineEdit.setGeometry(QtCore.QRect(330, 190, 271, 41))
        self.meter_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.meter_lineEdit.setObjectName("meter_lineEdit")
        self.feet_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.feet_lineEdit.setGeometry(QtCore.QRect(330, 280, 271, 41))
        self.feet_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.feet_lineEdit.setObjectName("feet_lineEdit")
        self.centimeter_lineEdit = QtWidgets.QLineEdit(parent=widget)
        self.centimeter_lineEdit.setGeometry(QtCore.QRect(330, 100, 271, 41))
        self.centimeter_lineEdit.setStyleSheet("* {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}")
        self.centimeter_lineEdit.setObjectName("centimeter_lineEdit")
        self.label_5 = QtWidgets.QLabel(parent=widget)
        self.label_5.setGeometry(QtCore.QRect(330, 240, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=widget)
        self.label_6.setGeometry(QtCore.QRect(330, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=widget)
        self.label_7.setGeometry(QtCore.QRect(330, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label.setText(_translate("widget", "Height and Weight Converter"))
        self.label_2.setText(_translate("widget", "Kilograms:"))
        self.label_3.setText(_translate("widget", "Pounds:"))
        self.label_4.setText(_translate("widget", "Ounces:"))
        self.label_5.setText(_translate("widget", "Feet:"))
        self.label_6.setText(_translate("widget", "Centimeters:"))
        self.label_7.setText(_translate("widget", "Meters:"))
