# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(300, 450)
        widget.setStyleSheet("background-color: black;")
        self.main_label = QtWidgets.QLabel(parent=widget)
        self.main_label.setGeometry(QtCore.QRect(20, 70, 261, 71))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(35)
        self.main_label.setFont(font)
        self.main_label.setStyleSheet("color: white")
        self.main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.main_label.setObjectName("main_label")
        self.main_label_2 = QtWidgets.QLabel(parent=widget)
        self.main_label_2.setGeometry(QtCore.QRect(20, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(18)
        self.main_label_2.setFont(font)
        self.main_label_2.setStyleSheet("color: white")
        self.main_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.main_label_2.setObjectName("main_label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 160, 281, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_decimal = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_decimal.setFont(font)
        self.button_decimal.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_decimal.setObjectName("button_decimal")
        self.gridLayout.addWidget(self.button_decimal, 3, 2, 1, 1)
        self.button_minus = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_minus.setFont(font)
        self.button_minus.setStyleSheet("background-color: #EEA10C;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 1, 3, 1, 1)
        self.button_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 2, 1, 1, 1)
        self.button_0 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_0.setFont(font)
        self.button_0.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 3, 0, 1, 2)
        self.button_1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 2, 0, 1, 1)
        self.button_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 2, 2, 1, 1)
        self.button_divide = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_divide.setFont(font)
        self.button_divide.setStyleSheet("background-color: #EEA10C;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_divide.setObjectName("button_divide")
        self.gridLayout.addWidget(self.button_divide, 3, 3, 1, 1)
        self.button_9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_9.setFont(font)
        self.button_9.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 0, 2, 1, 1)
        self.button_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 0, 1, 1, 1)
        self.button_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 1, 1, 1, 1)
        self.button_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 1, 2, 1, 1)
        self.button_plus = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_plus.setFont(font)
        self.button_plus.setStyleSheet("background-color: #EEA10C;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 0, 3, 1, 1)
        self.button_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 1, 0, 1, 1)
        self.button_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("background-color: #2A322E;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 0, 0, 1, 1)
        self.button_multi = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_multi.setFont(font)
        self.button_multi.setStyleSheet("background-color: #EEA10C;\n"
"color: white;\n"
"border-radius: 50px;")
        self.button_multi.setObjectName("button_multi")
        self.gridLayout.addWidget(self.button_multi, 2, 3, 1, 1)
        self.button_c = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_c.setFont(font)
        self.button_c.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 50px;")
        self.button_c.setObjectName("button_c")
        self.gridLayout.addWidget(self.button_c, 4, 0, 1, 2)
        self.button_equals = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_equals.setFont(font)
        self.button_equals.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 50px;")
        self.button_equals.setObjectName("button_equals")
        self.gridLayout.addWidget(self.button_equals, 4, 2, 1, 2)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.main_label.setText(_translate("widget", "0"))
        self.main_label_2.setText(_translate("widget", "0"))
        self.button_decimal.setText(_translate("widget", "."))
        self.button_minus.setText(_translate("widget", "-"))
        self.button_2.setText(_translate("widget", "2"))
        self.button_0.setText(_translate("widget", "0"))
        self.button_1.setText(_translate("widget", "1"))
        self.button_3.setText(_translate("widget", "3"))
        self.button_divide.setText(_translate("widget", "/"))
        self.button_9.setText(_translate("widget", "9"))
        self.button_8.setText(_translate("widget", "8"))
        self.button_5.setText(_translate("widget", "5"))
        self.button_6.setText(_translate("widget", "6"))
        self.button_plus.setText(_translate("widget", "+"))
        self.button_4.setText(_translate("widget", "4"))
        self.button_7.setText(_translate("widget", "7"))
        self.button_multi.setText(_translate("widget", "*"))
        self.button_c.setText(_translate("widget", "C"))
        self.button_equals.setText(_translate("widget", "="))
